<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\CartaJualan;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\CartaJualan>
 */
class CartaJualanFactory extends Factory
{
    protected $model = CartaJualan::class;

    public function definition(): array
    {
        return [
            'kategori' => fake()->word(),
        ];
    }
}
