<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Providers;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;

/**
 * Localization module registration (Fixzy SysMaker generated code).
 *
 * Registers the locale-switch route used by the user-menu switcher.
 * Only the two supported locale codes are accepted; anything else is
 * rejected with 404.
 */
class LocalizationServiceProvider extends ServiceProvider
{
    /**
     * Register the /fixzy-locale/{code} locale switch route.
     */
    public function boot(): void
    {
        Route::middleware(['web'])
            ->get('/fixzy-locale/{code}', function (string $code) {
                if (! in_array($code, ['en', 'ms'], true)) {
                    abort(404);
                }
                session()->put('fixzy_locale', $code);

                return redirect()->back();
            })
            ->name('fixzy.locale.switch');
    }
}
