<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Exports;

use App\Models\BookableResource;
use Filament\Actions\Exports\ExportColumn;
use Filament\Actions\Exports\Exporter;
use Filament\Actions\Exports\Models\Export;
use Illuminate\Support\Number;

/**
 * Generated exporter for Bookable Resources records (CSV/XLSX).
 */
class BookableResourceExporter extends Exporter
{
    protected static ?string $model = BookableResource::class;

    /**
     * Columns included in the export.
     * @return  array  Export column definitions.
     */
    public static function getColumns(): array
    {
        return [
                        ExportColumn::make('id')->limit(50)->label('Id'),
            ExportColumn::make('created_at')->limit(50)->label('Created At'),
            ExportColumn::make('updated_at')->limit(50)->label('Updated At'),
            ExportColumn::make('deleted_at')->limit(50)->label('Deleted At'),
            ExportColumn::make('created_by')->limit(50)->label('Created By'),
            ExportColumn::make('updated_by')->limit(50)->label('Updated By'),
            ExportColumn::make('deleted_by')->limit(50)->label('Deleted By'),
            ExportColumn::make('resource_name')->limit(50)->label('Resource Name'),
            ExportColumn::make('resource_code')->limit(50)->label('Resource Code'),
            ExportColumn::make('capacity')->limit(50)->label('Capacity'),
            ExportColumn::make('location')->limit(50)->label('Location'),
            ExportColumn::make('is_active')->limit(50)->label('Active'),
        ];
    }

    /**
     * Notification body shown when the export finishes.
     *
     * @param  Export  $export  The completed export job.
     * @return  string  Human-readable completion summary.
     */
    public static function getCompletedNotificationBody(Export $export): string
    {
        $body = 'Your Bookable Resources export has completed and ' . Number::format($export->successful_rows) . ' ' . str('row')->plural($export->successful_rows) . ' exported.';

        if ($failedRowsCount = $export->getFailedRowsCount()) {
            $body .= ' ' . Number::format($failedRowsCount) . ' ' . str('row')->plural($failedRowsCount) . ' failed to export.';
        }

        return $body;
    }
}
