// Contextual help registry — AppGini-style side panel content.
// Keyed by control id. Each entry: { title, body, tip? }
// Fallback per tab: HELP_TABS[tabId] = { title, body }
// Keep bodies 1-3 sentences. English only (publish-ready).

export const HELP_TABS = {
  'tab-stack': {
    title: 'Technologies Stack & Core Features',
    body: 'Choose the base framework and toggle the core modules every generated app can use: authentication, permissions, logging, real-time, sync, scheduler, backups and demo data. Everything here is decided once per project and shapes the generated code.'
  },
  'tab-localization': {
    title: 'Localization',
    body: 'Set the display language, time zone and date/time formats used across the generated app. These apply to every screen, report and export.'
  },
  'tab-models-design': {
    title: 'Models Design',
    body: 'Define your database: tables and their fields. Pick a table in the sidebar to edit its name and constraints, or a field to edit type, length, validation and display behaviour. Everything else in the app is built from this structure.'
  },
  'tab-modules-setup': {
    title: 'Modules Setup',
    body: 'Per-table behaviour: how the Table List looks and acts, what the Record Form allows, imports/exports, APIs, approvals, public forms and parent-child relations. Select a table in the sidebar first.'
  },
  'tab-menu-appearance': {
    title: 'Menu management',
    body: 'Control the navigation menu: orientation, homepage layout and how table panels are sized. Menu groups and items are managed in the sidebar tree.'
  },
  'tab-theme': {
    title: 'Theme',
    body: 'Pick a colour theme for the generated admin panel, or define your own primary colour and save it as a reusable theme.'
  },
  'tab-dashboard-builder': {
    title: 'Dashboard Builder',
    body: 'Compose the generated app dashboard from widgets: stat cards, tables and every chart type. Each widget reads from one table; arrange width, colour, filters and live-update behaviour.'
  },
  'tab-architecture': {
    title: 'Architecture & Multi-Tenancy',
    body: 'Configure multi-tenant architecture: which table represents the tenant, and which tables are scoped so each tenant only sees its own records.'
  },

  'tab-security': {
    title: 'Security & technical',
    body: 'Generated-app security switches: admins group access (Shield), a read-only server status page, and PWA install for the admin panel.'
  },
  'tab-hooks': {
    title: 'Hooks',
    body: 'Optional custom logic that runs on project events. For advanced use — most apps never need this.'
  },
  'getting-started': {
    title: 'Getting started',
    body: 'Build your app in three steps: 1) Design your tables and fields in Models Design. 2) Tune each table in Modules Setup (list, form, permissions). 3) Press Generate. Use this panel any time: click or focus any field and its explanation appears here.'
  }
};

export const HELP_ENTRIES = {
  // ============ Technologies Stack ============
  'app-stack_base': { title: 'Base stack', body: 'The framework combination the app is generated on. Laravel + Filament is the current target; the IR stays engine-neutral so more stacks can be added.' },
  'app-module-auth-email': { title: 'Email & Password authentication', body: 'The classic sign-in: users register or are invited with an email and password. Recommended for almost every app.', tip: 'Leave this on unless you use LDAP or SSO only.' },
  'app-module-auth-email-2fa': { title: 'Two-Factor Authentication (2FA)', body: 'Adds a second step after the password: a time-based code (TOTP) from an authenticator app like Google Authenticator or Authy.' },
  'app-module-auth-email-captcha': { title: 'Login captcha', body: 'A human check on the login form to slow down brute-force bots. The built-in arithmetic captcha needs no external service or API key.' },
  'app-module-auth-ldap': { title: 'LDAP authentication', body: 'Sign in against your organisation\'s LDAP/Active Directory instead of local accounts. Requires a reachable LDAP server and bind credentials.' },
  'app-module-auth-google-sso': { title: 'Google SSO', body: 'One-click sign-in with a Google account via OAuth. You supply a Google OAuth client ID/secret from the Google Cloud Console.' },
  'app-module-authorization': { title: 'Group-Based Permissions', body: 'Creates user groups (roles) with per-module and per-action permissions (view, create, edit, delete). Users get permissions through their group.', tip: 'This is the backbone of who-can-do-what — recommended for any multi-user app.' },
  'app-module-log-audit': { title: 'User Activity Log', body: 'Records what users did in the app: sign-ins, sign-outs, failed attempts, page visits. A security/behaviour log.' },
  'app-module-log-activity': { title: 'Data Audit Trail', body: 'Records who changed what data: create/edit/delete with before-and-after values per field. Different from the activity log — the two are complementary.', tip: 'Enable both for full accountability.' },
  'app-module-realtime': { title: 'Real-time module', body: 'Pushes events to users instantly instead of waiting for refresh: live notification bell, live workflow notices, and live dashboard widgets.' },
  'app-realtime_backend': { title: 'Real-time backend', body: 'The transport used to push events. Choose based on your hosting: a dedicated WebSocket server (Reverb) for scale, or polling for simple deployments.' },
  'app-module-google-sheets': { title: 'Google Sheets Sync', body: 'Turns any custom table into a live Google Spreadsheet. Rows added or edited in the sheet sync back into the database automatically (and vice versa).' },
  'app-module-scheduler': { title: 'Scheduler module', body: 'Time-based automation: date reminders (notify a role N days before a date), recurring records (auto-clone a row daily/weekly/monthly), and scheduled backups. Required for the backup options below.' },
  'app-backup-enabled': { title: 'Scheduled database backups', body: 'Takes automatic database backups on a fixed schedule and stores them on the server.' },
  'app-backup-frequency': { title: 'Backup frequency', body: 'How often backups run: hourly, daily, weekly or monthly.' },
  'app-backup-weekday': { title: 'Backup weekday', body: 'Which day of the week the weekly backup runs.' },
  'app-backup-retention': { title: 'Keep last N backups', body: 'Older backups beyond this count are deleted automatically so disk usage stays bounded.' },
  'app-backup-notify': { title: 'Notify roles', body: 'Comma-separated role names that receive a notification after each backup (success or failure).' },
  'app-module-fake-data': { title: 'Include Data Seeder', body: 'Generates realistic-looking sample records for every table. Great for demos, screenshots and learning how the app behaves with data.' },
  'app-debug-mode': { title: 'Debug Mode & Debugbar', body: 'Shows detailed error pages and a developer debugbar (queries, memory, timing). Turn OFF in production — it leaks internals.', tip: 'Never enable on a public production server.' },

  // ============ Localization ============
  'app-date-preview': { title: 'Date/time preview', body: 'A live preview of how dates and times will look with the formats you picked. Read-only.' },
  'app-date-format': { title: 'Date format', body: 'How dates display across the app (day/month/year vs month/day/year etc.). Applies to lists, forms, reports and exports.' },
  'app-time-format': { title: 'Time format', body: '12-hour or 24-hour clock for all time displays in the generated app.' },
  'app-language-select': { title: 'Language', body: 'The admin panel UI language. Labels, buttons and messages are translated to the selected language.' },
  'app-timezone-select': { title: 'Time zone', body: 'The app\'s working time zone. Timestamps are stored consistently and displayed in this zone.' },

  // ============ Models Design — table level ============
  'tbl-table-name': { title: 'Table name (in database)', body: 'The physical table name in the database. Lowercase with underscores (snake_case). This is what migrations and queries use.' },
  'tbl-module-name': { title: 'Default Module name', body: 'The human name used in menus, breadcrumbs and page titles for this table\'s module.' },
  'constraint-type-select': { title: 'Constraint rule type', body: 'The kind of table-level rule to add, e.g. a composite UNIQUE key spanning several columns.' },
  'constraint-fields-select': { title: 'Constraint fields', body: 'The columns the rule applies to. Use Ctrl/Cmd + Click to select multiple fields.' },

  // ============ Models Design — field basics ============
  'fld-field-name': { title: 'Field name (in database)', body: 'The physical column name. Lowercase snake_case, no spaces. Used in queries, exports and code.' },
  'fld-caption': { title: 'Caption', body: 'The human label shown above the input and as the column header in the Table List.' },
  'fld-caption-ms': { title: 'Caption (Malay)', body: 'Malay translation of the caption, shown when the app language is Malay.' },
  'fld-description': { title: 'Description', body: 'A longer note about this field for documentation and tooltips.' },
  'fld-data-type': { title: 'Data type', body: 'The database column type: string, text, integer, decimal, date, datetime, boolean, json and so on. Drives the input control and validation.' },
  'fld-length': { title: 'Length', body: 'Maximum stored length for text types (VARCHAR). Keep it tight for codes, generous for names.' },
  'fld-precision': { title: 'Precision', body: 'Decimal places for decimal/money types, e.g. 10,2 stores up to 99,999,999.99.' },
  'fld-alignment': { title: 'Alignment', body: 'How the value aligns in the Table List column: left, center or right. Numbers usually look best right-aligned.' },
  'fld-default-value': { title: 'Default', body: 'Value pre-filled when a new record is created. Users can change it unless the field is read-only.' },
  'fld-primary-key': { title: 'Primary Key', body: 'Marks this field as the unique row identifier. Every table needs exactly one; leave the auto-generated id as the PK unless you know why to change it.' },
  'fld-auto-increment': { title: 'Auto Increment', body: 'The database assigns the next number automatically on insert. Standard for integer primary keys.' },
  'fld-unique': { title: 'Unique (No duplicates)', body: 'The database rejects a value that already exists in this column. Use for emails, codes, registration numbers.' },
  'fld-not-null': { title: 'Not Null', body: 'A database-level constraint that forbids empty (NULL) values. Stronger than "Required" which is form-level.' },
  'fld-is-indexed': { title: 'Index', body: 'Speeds up lookups and sorting on this column. Recommended for fields used in filters, joins and search.' },
  'fld-unsigned': { title: 'Unsigned', body: 'Only allows positive numbers (0 and above). Ideal for ID fields.' },
  'fld-zero-fill': { title: 'Zero Fill', body: 'Pads numbers with leading zeros up to the specified length (e.g. 5 becomes 00005). Useful for display codes.' },
  'fld-binary': { title: 'Binary', body: 'Treats the column as binary data (case-sensitive comparisons). Rarely needed — leave off unless required.' },

  // ============ Field media ============
  'fld-media-link': { title: 'Link field', body: 'Stores a URL and renders it as a clickable link in lists and forms.' },
  'fld-media-image': { title: 'Image field', body: 'Stores an image (URL or uploaded file) and renders a thumbnail in the Table List and the image in the Record Form.' },
  'fld-media-upload': { title: 'File upload', body: 'A single file attached to the record, stored on the server\'s private storage.' },
  'fld-media-attachments': { title: 'Attachments (multi-file)', body: 'Multiple files per record, stored as attachment rows with metadata (who uploaded, when, size). Files are kept in private storage.' },
  'fld-media-gmap': { title: 'Google map field', body: 'Stores a location and renders an interactive map pin in the record.' },
  'fld-media-youtube': { title: 'YouTube field', body: 'Stores a YouTube URL and embeds the video player in the record form.' },
  'fld-media-link-behavior': { title: 'Link click behaviour', body: 'What happens when the link is clicked in the Table List: open in a new tab, same tab, or copy to clipboard.' },
  'fld-media-link-display-as': { title: 'Link display', body: 'What text the link shows: the raw URL, a caption from another field, or a fixed label.' },
  'fld-media-link-other-field': { title: 'The other field', body: 'The field whose value is used as the link\'s display text (when display-as = other field).' },
  'fld-allow-image-uploads': { title: 'Allow image uploads', body: 'Lets users upload an image file instead of only pasting a URL.' },
  'fld-image-storage-provider': { title: 'Image storage provider', body: 'Where uploaded images are stored: local server disk or a cloud bucket (S3-compatible).' },
  'fld-max-file-size': { title: 'Maximum file size (KB)', body: 'Uploads larger than this are rejected. Keep it reasonable for your hosting limits.' },
  'fld-delete-image-server': { title: 'Delete files from server', body: 'When the image is removed from the record (or the record deleted), the file is deleted from storage too.' },
  'fld-dont-rename-image': { title: 'Don\'t rename image', body: 'Keep the original filename instead of generating a unique one. Risk: filename collisions.' },
  'fld-tv-thumb-shape': { title: 'Thumbnail shape (Table List)', body: 'Thumbnail crop style in the list: square, circle or rounded rectangle.' },
  'fld-tv-thumb-width': { title: 'Thumbnail width (Table List)', body: 'Thumbnail width in pixels in the Table List.' },
  'fld-tv-thumb-height': { title: 'Thumbnail height (Table List)', body: 'Thumbnail height in pixels in the Table List.' },
  'fld-tv-enable-zooming': { title: 'Enable zooming (Table List)', body: 'Clicking the thumbnail opens a zoomed lightbox view.' },
  'fld-tv-show-full-size': { title: 'Show full size (Table List)', body: 'Show the full-size image instead of a scaled thumbnail in the list.' },
  'fld-dv-thumb-shape': { title: 'Thumbnail shape (Record Form)', body: 'Thumbnail crop style shown in the Record Form.' },
  'fld-dv-thumb-width': { title: 'Thumbnail width (Record Form)', body: 'Thumbnail width in pixels in the Record Form.' },
  'fld-dv-thumb-height': { title: 'Thumbnail height (Record Form)', body: 'Thumbnail height in pixels in the Record Form.' },
  'fld-dv-enable-zooming': { title: 'Enable zooming (Record Form)', body: 'Clicking the image in the form opens a zoomed lightbox view.' },
  'fld-dv-show-full-size': { title: 'Show full size (Record Form)', body: 'Render the full-size image in the form instead of a thumbnail.' },
  'fld-allow-file-uploads': { title: 'Allow file uploads', body: 'Enables file upload for this field instead of URL-only entry.' },
  'fld-file-storage-provider': { title: 'File storage provider', body: 'Where uploaded files are stored: local server disk or a cloud bucket (S3-compatible).' },
  'fld-file-types': { title: 'Allowed file types', body: 'Comma-separated extensions accepted on upload, e.g. pdf,docx,xlsx. Leave empty to allow any type.' },
  'fld-file-max-size': { title: 'File max size (KB)', body: 'Uploads larger than this are rejected.' },
  'fld-delete-file-server': { title: 'Delete files from server', body: 'Removing the file from the record also deletes it from storage.' },
  'fld-dont-rename-file': { title: 'Don\'t rename file', body: 'Keep the original filename instead of a generated unique name.' },
  'fld-file-behavior': { title: 'File click behaviour', body: 'What happens when the file link is clicked in the Table List: download, open, or copy link.' },
  'fld-file-display-as': { title: 'File display', body: 'The link text shown for the file: filename, fixed label, or another field\'s value.' },
  'fld-file-other-field': { title: 'The other field', body: 'Field used as the display text for the file link.' },
  'fld-attach-max-files': { title: 'Maximum files per record', body: 'Cap on how many attachments one record can hold.' },
  'fld-attach-types': { title: 'Allowed attachment types', body: 'Comma-separated extensions allowed. Leave empty = any type.' },
  'fld-attach-max-size': { title: 'Attachment max size (KB)', body: 'Per-file size cap for attachments.' },
  'fld-display-gmap': { title: 'Display Google map', body: 'Renders the stored location as an interactive map in the record.' },
  'fld-fld-gmap-type-url': { title: 'Map from URL', body: 'Show a map using a user-provided map URL.' },
  'fld-fld-gmap-type-pin-new': { title: 'Pin at save (new)', body: 'Captures the user\'s location at the time a new record is saved and pins it on the map.' },
  'fld-fld-gmap-type-pin-capture': { title: 'Pin at save (new or existing)', body: 'Captures the user\'s location whenever any record is saved, new or existing.' },
  'fld-gmap-tv-width': { title: 'Map width (Table List)', body: 'Map preview width in pixels in the list.' },
  'fld-gmap-tv-height': { title: 'Map height (Table List)', body: 'Map preview height in pixels in the list.' },
  'fld-gmap-dv-height': { title: 'Map height (Record Form)', body: 'Map height in pixels in the record form.' },
  'fld-accept-video-url': { title: 'Accept video URL', body: 'Accepts a YouTube URL and embeds the player.' },
  'fld-youtube-tv-width': { title: 'Video max width (Table List)', body: 'Embedded video max width in the list.' },
  'fld-youtube-tv-height': { title: 'Video max height (Table List)', body: 'Embedded video max height in the list.' },
  'fld-youtube-dv-width': { title: 'Video max width (Record Form)', body: 'Embedded video max width in the form.' },
  'fld-youtube-dv-height': { title: 'Video max height (Record Form)', body: 'Embedded video max height in the form.' },

  // ============ Lookup fields ============
  'fld-lookup-parent-table': { title: 'Parent table', body: 'The table this field points to (foreign key). The dropdown lists records from this table.' },
  'fld-lookup-caption-1': { title: 'Caption part 1', body: 'First column from the parent table used to build the dropdown label (e.g. first name).' },
  'fld-lookup-separator': { title: 'Separator', body: 'Text placed between caption parts, e.g. a space or dash.' },
  'fld-lookup-caption-2': { title: 'Caption part 2', body: 'Second column from the parent table for the dropdown label (e.g. last name).' },
  'fld-lookup-inherit-permissions': { title: 'Inherit access permissions', body: 'The dropdown only shows parent records the user is allowed to see, using the parent table\'s permissions.' },
  'fld-lookup-searchable': { title: 'Searchable lookup', body: 'Turns the dropdown into a type-ahead search — essential when the parent table has many records.' },
  'fld-lookup-preload': { title: 'Preload options', body: 'Loads all parent options up front instead of on-demand. Fine for small lists; avoid for large ones.' },
  'fld-lookup-link-behavior': { title: 'Link to parent record', body: 'In the Record Form, shows a link that opens the selected parent record.' },
  'fld-lookup-custom-query-hidden': { title: 'Custom lookup query', body: 'Advanced: a custom SQL query that decides which parent records appear in the dropdown. Must return the parent PK and a caption column.' },
  'fld-lookup-custom-query': { title: 'Custom lookup query', body: 'SQL used to fetch lookup items. The first column must be the parent table\'s primary key; the second is the caption. Reset restores the default query.' },

  // ============ Field form & visibility ============
  'fld-label-display': { title: 'Label position', body: 'Where the field label sits: above the input, beside it (inline), or hidden.' },
  'fld-form-group': { title: 'Form group', body: 'Assigns this field to a named section in the record form (used by the Form Layout designer).' },
  'fld-vis-field': { title: 'Visibility: other field', body: 'This field is shown/hidden depending on the value of this other field.' },
  'fld-vis-op': { title: 'Visibility: condition', body: 'The comparison used: is, is not, is one of, is empty, etc.' },
  'fld-vis-value': { title: 'Visibility: value', body: 'The value (comma-separated for "is one of") that triggers showing this field.' },
  'fld-dep-field': { title: 'Dependent dropdown: parent field', body: 'This lookup\'s options are filtered by the chosen value of this parent field — e.g. slots filtered by the chosen Room.' },
  'fld-dep-filter': { title: 'Dependent dropdown: filter column', body: 'The column on this field\'s lookup table that matches the parent field\'s value.' },
  'fld-dep-count': { title: 'Remaining-count helper', body: 'Optional helper column that shows how many options remain after filtering (e.g. seats left).' },
  'fld-req-field': { title: 'Conditional required: other field', body: 'This field becomes required when the other field meets the condition.' },
  'fld-req-op': { title: 'Conditional required: condition', body: 'The comparison: is, is not, is one of, is filled, etc.' },
  'fld-req-value': { title: 'Conditional required: value', body: 'The value (comma-separated for "is one of") that makes this field required.' },
  'fld-calculated-enable': { title: 'Calculated field', body: 'The value is computed from a query over the record/related tables instead of typed by the user.' },
  'fld-calculated-query': { title: 'Calculation query', body: 'The SQL expression that computes this field\'s value on save.' },
  'fld-algorithm-enable': { title: 'Algorithm field', body: 'Runs custom logic (algorithm builder) to compute this field on save.' },
  'fld-algorithm-logic': { title: 'Algorithm logic', body: 'The step-by-step logic produced by the Algorithm Builder that computes this field.' },

  // ============ Modules Setup — list & grid ============
  'workspace-base-table-select': { title: 'Base Table', body: 'Pick the table whose settings you are editing. All options on this tab apply to the selected table.' },
  'workspace-new-module-name': { title: 'New module name', body: 'Create a new module (table view) based on the selected base table with a different name/layout.' },
  'tbl-table-view-title': { title: 'Table List title', body: 'The heading shown above the list of records for this module.' },
  'tbl-table-description': { title: 'Table description', body: 'A short description shown under the Table List title.' },
  'tbl-show-quick-search': { title: 'Quick search box', body: 'Adds a search box that filters the list across searchable columns.' },
  'tbl-allow-pagination': { title: 'Pagination', body: 'Splits long lists into pages instead of rendering everything at once.' },
  'tbl-default-sort-by': { title: 'Default sort by', body: 'The column the list is sorted by when opened.' },
  'tbl-sort-descending': { title: 'Sort descending', body: 'Sort newest/highest first instead of ascending.' },
  'tbl-grid-column-manager': { title: 'Column chooser', body: 'Users can show/hide and reorder columns themselves (Horizontal template only).' },
  'tbl-grid-sticky-header': { title: 'Sticky column headers', body: 'The header row stays visible while scrolling long lists.' },
  'tbl-grid-inline-edit': { title: 'Inline edit', body: 'Users can edit values directly in the Table List without opening the Record Form.' },
  'tbl-grid-row-density': { title: 'Row density', body: 'Compact, normal or comfortable row height — controls how many rows fit on screen.' },
  'tbl-grid-default-per-page': { title: 'Default records per page', body: 'How many rows show per page initially.' },
  'tbl-grid-per-page-options': { title: 'Per-page choices', body: 'The page-size options offered to users, comma-separated (e.g. 10,25,50,100).' },
  'tbl-grid-group-by': { title: 'Group rows by column', body: 'Groups rows under headers by a column\'s value (Horizontal template only).' },
  'tbl-grid-group-direction': { title: 'Group direction', body: 'Sort direction within each group: ascending or descending.' },
  'tbl-grid-summaries': { title: 'Summary row', body: 'Shows totals/averages for numeric columns at the bottom of the list (Horizontal template).' },
  'tbl-grid-row-click': { title: 'When a row is clicked', body: 'What a row click does: open the Record Form, expand inline, or do nothing.' },
  'tbl-grid-empty-heading': { title: 'Empty state heading', body: 'Heading shown when the table has no records yet.' },
  'tbl-grid-empty-icon': { title: 'Empty state icon', body: 'Icon shown in the empty state.' },
  'tbl-grid-empty-description': { title: 'Empty state description', body: 'Helper text shown in the empty state.' },
  'tbl-grid-row-striping': { title: 'Row striping & borders', body: 'Alternating row background and border styling for readability.' },
  'tbl-grid-border-style': { title: 'Border style', body: 'Cell border style: none, horizontal only, or full grid.' },
  'tbl-grid-content-width': { title: 'Table content width', body: 'How wide the table content stretches: fit to content or fill the screen.' },
  'tbl-grid-sticky-toolbar': { title: 'Sticky toolbar', body: 'Keeps the toolbar (search, buttons) visible while scrolling.' },
  'tbl-grid-sticky-footer': { title: 'Sticky footer', body: 'Keeps the pagination footer visible while scrolling.' },
  'tbl-grid-multi-view': { title: 'Multiple views', body: 'Offers several saved view configurations users can switch between.' },
  'tbl-grid-view-default': { title: 'Default view', body: 'The view shown first when the module opens.' },
  'tbl-grid-split-view': { title: 'Split view', body: 'List on the left, selected record detail on the right.' },
  'tbl-grid-calendar-enabled': { title: 'Calendar view', body: 'Adds a calendar view of this table\'s dated records.' },
  'tbl-cal-start': { title: 'Calendar start field', body: 'The date field that sets each event\'s start.' },
  'tbl-cal-end': { title: 'Calendar end field', body: 'Optional end date field for multi-day events.' },
  'tbl-cal-title': { title: 'Calendar title field', body: 'The field whose value labels each calendar event.' },
  'tbl-cal-color': { title: 'Calendar colour', body: 'Event colour, fixed or derived from a field.' },
  'tbl-grid-calendar-config': { title: 'Calendar configuration', body: 'Summary of the calendar view mapping (start, end, title, colour).' },
  'tbl-grid-tree-enabled': { title: 'Tree view', body: 'Displays records as a hierarchy (parent → children) instead of a flat list.' },
  'tbl-tree-parent': { title: 'Tree parent field', body: 'The self-referencing foreign key that defines the hierarchy.' },
  'tbl-tree-label': { title: 'Tree label field', body: 'The field shown as each tree node\'s label.' },
  'tbl-grid-tree-config': { title: 'Tree configuration', body: 'Summary of the tree view mapping (parent field, label field).' },
  'tbl-grid-kanban-enabled': { title: 'Kanban view', body: 'Adds a drag-and-drop kanban board for this table.' },
  'tbl-kanban-group': { title: 'Kanban group column', body: 'The status-like column whose values become the board columns.' },
  'tbl-kanban-cards': { title: 'Kanban card fields', body: 'Fields shown on each card.' },
  'tbl-kanban-transitions': { title: 'Kanban transitions', body: 'Allowed moves between board columns (drag rules).' },
  'tbl-grid-kanban-config': { title: 'Kanban configuration', body: 'Summary of the kanban mapping (group column, cards, transitions).' },
  'tbl-grid-column-groups': { title: 'Column groups', body: 'Visually group related columns under a shared header (Horizontal template).' },
  'tbl-allow-csv-export': { title: 'CSV export', body: 'Adds an export button so users can download the list as CSV (XLSX is also supported natively).' },
  'tbl-allow-csv-import': { title: 'CSV import', body: 'Lets users upload a CSV to create/update records. The match field decides how rows are matched.' },
  'tbl-allow-print-view': { title: 'Print view', body: 'Adds a print-optimised view of the records.' },
  'tbl-allow-mass-delete': { title: 'Bulk delete', body: 'Users can select multiple rows and delete them at once.' },
  'tbl-google-sync-enabled': { title: 'Google Sheets sync', body: 'Exposes this table as a live Google Spreadsheet (requires the Google Sheets module in Technologies Stack).' },
  'tbl-attachments-enabled': { title: 'File attachments', body: 'Enables multi-file attachments on this table (private storage).' },
  'tbl-show-edit-button': { title: 'Show edit button', body: 'Shows the edit action button on each row.' },
  'tbl-show-delete-button': { title: 'Show delete button', body: 'Shows the delete action button on each row.' },
  'tbl-allow-restore-delete': { title: 'Allow restore (Soft Delete)', body: 'Deleted records are marked deleted (deleted_at) but kept, and can be restored. Requires the soft-delete strategy.' },
  'tbl-allow-force-delete': { title: 'Allow force delete', body: 'Permanently removes records (DELETE FROM). Irreversible — usually admin-only.' },
  'tbl-tv-template': { title: 'Table List template', body: 'The list layout: horizontal table, card grid, or other templates.' },
  'tbl-card-columns-tablet': { title: 'Card columns (tablet)', body: 'How many cards per row on tablet-width screens.' },
  'tbl-card-columns': { title: 'Card columns (desktop)', body: 'How many cards per row on desktop-width screens.' },
  'tbl-hide-field-captions': { title: 'Hide field captions', body: 'Hides the field labels in the list/form for a denser look.' },
  'tbl-use-first-field-as-title': { title: 'First field as title', body: 'Uses the first visible field\'s value as the record title in cards and headers.' },
  'tbl-table-view-classes-input': { title: 'Table List classes', body: 'Extra CSS classes applied to the Table List container for custom styling.' },
  'table-view-classes-select': { title: 'Table List classes', body: 'Pick from available style classes for the Table List.' },
  'tbl-detail-view-classes-input': { title: 'Record Form classes', body: 'Extra CSS classes applied to the Record Form container.' },
  'detail-view-classes-select': { title: 'Record Form classes', body: 'Pick from available style classes for the Record Form.' },
  'tbl-detail-view-title': { title: 'Record Form title', body: 'The heading shown on the record form.' },
  'tbl-record-owner': { title: 'Data Accessibility (Scoping)', body: 'Restricts which records a user sees based on ownership — e.g. only their own records, or their group\'s.' },
  'tbl-default-focus': { title: 'Default focus field', body: 'The field focused when the record form opens — speeds up data entry.' },
  'tbl-redirect-after-insert': { title: 'Redirect after insert', body: 'After saving a new record, go back to the list instead of staying on the form.' },
  'tbl-enable-detail-view': { title: 'Enable Record Form', body: 'Turns the detail/record form on or off for this table.' },
  'tbl-delete-with-children': { title: 'Delete with children', body: 'Allow deleting a record even if related child records exist (children are deleted or detached per strategy).' },
  'tbl-dv-allow-print-view': { title: 'Record print view', body: 'Adds a print button to the record form.' },
  'tbl-dv-separate-page': { title: 'Separate page form', body: 'Opens the Record Form on its own page instead of a modal popup.' },
  'tbl-dv-hide-save-as-copy': { title: 'Hide "Save As Copy"', body: 'Hides the duplicate-record button in the form.' },
  'tbl-dv-sticky-buttons': { title: 'Sticky action buttons', body: 'Save/cancel buttons stay visible while scrolling a long form.' },
  'tbl-dv-allow-add-from-homepage': { title: 'Add from homepage', body: 'Lets users create records of this table directly from the homepage.' },
  'tbl-column-grid-dynamic': { title: 'Dynamic column grid', body: 'The form auto-arranges fields into columns based on width.' },
  'tbl-column-grid-static': { title: 'Static column grid', body: 'Uses a fixed number of form columns you set below.' },
  'tbl-static-grid-columns': { title: 'Number of grids', body: 'How many columns the static form grid has.' },
  'tbl-numbering-enabled': { title: 'Auto reference numbers', body: 'Auto-fills a column with a race-safe reference code on create (e.g. INV-202609-0001).' },
  'num-field': { title: 'Target column', body: 'The column that receives the generated reference number.' },
  'num-prefix': { title: 'Prefix', body: 'Fixed text before the number, e.g. "INV-".' },
  'num-token': { title: 'Date part', body: 'Optional date fragment in the code, e.g. YYYYMM for a monthly sequence.' },
  'num-width': { title: 'Sequence width', body: 'Digit count of the sequence, e.g. 4 → 0001, 0002.' },
  'tbl-import-enabled': { title: 'Import enabled', body: 'Enables CSV import for this table.' },
  'imp-match-field': { title: 'Match field', body: 'The column used to find an existing record during import (e.g. email or code).' },
  'imp-mode': { title: 'On match', body: 'When a match is found: update the existing row, skip it, or always insert a new one.' },
  'imp-dry-run': { title: 'Dry run', body: 'Validates the import and reports what would happen without saving anything.' },
  'tbl-api-enabled': { title: 'REST API', body: 'Exposes this table over a token-authenticated JSON API (/api/v1/...). Sensitive columns (passwords, tokens, secrets) are never exposed.' },
  'api-read-roles': { title: 'Read roles', body: 'Comma-separated Shield roles allowed to read this table via the API. Leave none checked to expose all non-sensitive columns.' },
  'api-write-roles': { title: 'Write roles', body: 'Roles allowed to create/update via the API.' },
  'api-rate-limit': { title: 'Rate limit (req/min per token)', body: 'Maximum API requests per minute per token — protects against abuse.' },
  'tbl-approval-enabled': { title: 'Approval workflow', body: 'Records move through your own statuses (e.g. Draft → Pending → Approved). Each step can require a comment and restrict who may move it.' },
  'approval-status-field': { title: 'Status field', body: 'The text column that holds the record\'s current status. It becomes a coloured badge in the list.' },
  'approval-preset': { title: 'Start from a preset', body: 'Fills the transition table below with a ready-made workflow. You can edit everything after.' },
  'scheduler-recurring-enabled': { title: 'Recurring creation', body: 'Auto-creates a copy of the latest row on a fixed cycle (e.g. a monthly bill). Optional: notify a role on each creation.' },
  'scheduler-recurring-day': { title: 'Day of month (1–31)', body: 'Which day of the month the recurring record is created.' },
  'scheduler-recurring-weekday': { title: 'Day of week', body: 'Which weekday the recurring record is created (for weekly cycles).' },
  'scheduler-recurring-notify': { title: 'Notify role(s)', body: 'Roles notified each time the recurring record is created.' },
  'tbl-hook-logic': { title: 'Table hooks', body: 'Custom logic that runs on this table\'s events (before/after save, delete, etc.).' },
  'tbl-public-form-enabled': { title: 'Public form', body: 'Lets guests submit records without logging in. Submissions land in this table with a generated reference number.' },
  'pf-slug': { title: 'Form URL slug', body: 'The public URL path for the form, e.g. /forms/feedback.' },
  'pf-intro': { title: 'Intro text', body: 'Text shown above the public form.' },
  'pf-success': { title: 'Success text', body: 'Message shown after a successful submission.' },
  'pf-status-default': { title: 'Initial status', body: 'Status set on new submissions (leave empty if this table has no status column).' },
  'pf-captcha': { title: 'Human check (captcha)', body: 'Requires a simple arithmetic captcha before accepting a submission — stops spam bots.' },
  'pf-lookup': { title: 'Guest-submittable fields', body: 'Tick the columns guests may submit. Everything else stays admin-only.' },

  // ============ Form layout ============
  'fl-style': { title: 'Form style', body: 'Shape the record form: grouped sections, multi-step wizard, accordion, inline labels, or the default single-section layout.' },
  'fl-columns': { title: 'Form columns', body: 'Number of columns in the form grid.' },
  'fl-label-display': { title: 'Default label position', body: 'Where labels sit by default: above or beside inputs.' },
  'fl-ungrouped-title': { title: 'Ungrouped fields section', body: 'Section title for fields not assigned to any group.' },
  'fl-wizard-start': { title: 'Start on step', body: 'Which wizard step the form opens on.' },
  'fl-wizard-skippable': { title: 'Skippable steps', body: 'Whether users may skip wizard steps.' },
  'fl-chat-slug': { title: 'Chat URL slug', body: 'URL slug for the conversational form version (defaults to the table name).' },
  'fl-chat-greeting': { title: 'Greeting message', body: 'First message shown in the conversational form.' },
  'fl-chat-farewell': { title: 'Farewell message', body: 'Closing message after the last question.' },

  // ============ Parent-child ============
  'parentchild-show-tab': { title: 'Show child tab', body: 'Shows related child records as a tab below the parent Record Form.' },
  'parentchild-show-icon': { title: 'Show icon', body: 'Shows an icon linking to the child records.' },
  'parentchild-autoclose-modal': { title: 'Auto-close modal', body: 'Closes the child add/edit modal automatically after saving.' },
  'parentchild-tab-title': { title: 'Tab/column title', body: 'The title of the child tab or column.' },
  'parentchild-copy-records': { title: 'Copy child records', body: 'When copying a parent record, also copy its child records.' },
  'parentchild-show-link-above': { title: 'Show link above form', body: 'Shows a link to child records above the Record Form.' },
  'parentchild-show-count-in-tv': { title: 'Show child count in list', body: 'Shows how many children each parent has in the Table List.' },
  'parentchild-allow-add-from-tv': { title: 'Add child from list', body: 'Lets users add a child record directly from the parent\'s row in the list.' },
  'parentchild-tv-template': { title: 'Child table template', body: 'The list layout used inside the child tab.' },
  'parentchild-card-columns': { title: 'Child card columns', body: 'Cards per row for child records on desktop.' },
  'parentchild-form-style': { title: 'Child form style', body: 'The create/edit modal style for child records.' },

  // ============ Field display in list ============
  'fld-hide-in-tv': { title: 'Hide in Table List', body: 'This field is not shown as a column in the Table List.' },
  'fld-editable-in-tv': { title: 'Editable in Table List', body: 'The value can be edited inline directly in the list (requires inline edit enabled on the table).' },
  'fld-allow-sorting': { title: 'Enable sorting', body: 'Users can sort the list by this column.' },
  'fld-enable-global-filter': { title: 'Global filter', body: 'This column participates in the global quick-search filter.' },
  'fld-enable-individual-filter': { title: 'Individual filter', body: 'Adds a per-column filter control in the list header.' },
  'fld-enable-range-filter': { title: 'Range filter', body: 'For numeric/date columns: filter by a from–to range.' },
  'fld-show-sum': { title: 'Show sum summary', body: 'Shows the column total in the summary row.' },
  'fld-show-avg-summary': { title: 'Show average summary', body: 'Shows the column average in the summary row.' },
  'fld-show-count-summary': { title: 'Show count summary', body: 'Shows the row count for this column in the summary row.' },
  'fld-show-range-summary': { title: 'Show range summary', body: 'Shows min–max range for this column in the summary row.' },
  'fld-tv-wrap-header': { title: 'Wrap column header', body: 'Long column headers wrap onto multiple lines instead of truncating.' },
  'fld-tv-wrap-text': { title: 'Enable wrap text', body: 'Cell text wraps instead of being cut off with ellipsis.' },
  'fld-tv-enable-toggle': { title: 'Toggle hidden by default', body: 'This column starts hidden; users can toggle it on via the column chooser.' },
  'fld-tv-description-tooltips': { title: 'Description tooltips', body: 'Shows the field description as a tooltip on hover in the list.' },
  'fld-tv-currency-code': { title: 'Currency code', body: 'Formats numeric values as currency with this code (e.g. MYR, USD).' },
  'fld-tv-alignment': { title: 'Column alignment', body: 'Text alignment for this column in the list.' },
  'fld-tv-text-limit': { title: 'Text limit', body: 'Truncates long text to this many characters with an ellipsis.' },
  'fld-tv-text-size': { title: 'Text size', body: 'Font size for this column in the list.' },
  'fld-tv-font-weight': { title: 'Font weight', body: 'Normal or bold text in this column.' },
  'fld-tv-text-color': { title: 'Text color', body: 'Text colour for this column.' },
  'fld-tv-icon': { title: 'Column icon', body: 'An icon shown before the value in this column.' },
  'fld-tv-icon-color': { title: 'Icon color', body: 'Colour of the column icon.' },

  // ============ Field form & validation ============
  'fld-hide-in-dv': { title: 'Hide in Record Form', body: 'This field is not shown in the record form (system/internal fields).' },
  'fld-required': { title: 'Required', body: 'The user must fill this field before saving. Form-level check (see Not Null for the database-level one).' },
  'fld-read-only': { title: 'Read only', body: 'The value cannot be edited by users in the form.' },
  'fld-helper-text': { title: 'Helper text', body: 'Small guidance text shown under the input in the form.' },
  'fld-placeholder': { title: 'Placeholder', body: 'Grey hint text inside the empty input.' },
  'fld-min-length': { title: 'Min length', body: 'Shortest accepted text length.' },
  'fld-max-length': { title: 'Max length', body: 'Longest accepted text length.' },
  'fld-min-value': { title: 'Min value', body: 'Smallest accepted number.' },
  'fld-max-value': { title: 'Max value', body: 'Largest accepted number.' },
  'fld-repeater-1-display-as': { title: 'Display As', body: 'How the list of values is presented: dropdown, radio buttons, checkboxes or tags.' },
  'fld-repeater-1-format-as': { title: 'Formatted Inputs', body: 'Input format applied to the entered value.' },
  'fld-repeater-1-list-values': { title: 'List values', body: 'The allowed options, separated by commas.' },
  'fld-repeater-1-required': { title: 'Required', body: 'A selection from this list is mandatory.' },
  'fld-repeater-2-display-as': { title: 'Display As', body: 'How the list of values is presented: dropdown, radio buttons, checkboxes or tags.' },
  'fld-repeater-2-format-as': { title: 'Formatted Inputs', body: 'Input format applied to the entered value.' },
  'fld-repeater-2-list-values': { title: 'List values', body: 'The allowed options, separated by commas.' },
  'fld-repeater-2-required': { title: 'Required', body: 'A selection from this list is mandatory.' },
  'fld-repeater-3-display-as': { title: 'Display As', body: 'How the list of values is presented: dropdown, radio buttons, checkboxes or tags.' },
  'fld-repeater-3-format-as': { title: 'Formatted Inputs', body: 'Input format applied to the entered value.' },
  'fld-repeater-3-list-values': { title: 'List values', body: 'The allowed options, separated by commas.' },
  'fld-repeater-3-required': { title: 'Required', body: 'A selection from this list is mandatory.' },
  'fld-repeater-simple-display-as': { title: 'Display As', body: 'How the list of values is presented: dropdown, radio buttons, checkboxes or tags.' },
  'fld-repeater-simple-format-as': { title: 'Formatted Inputs', body: 'Input format applied to the entered value.' },
  'fld-repeater-simple-list-values': { title: 'List values', body: 'The allowed options, separated by commas.' },
  'fld-repeater-simple-required': { title: 'Required', body: 'A selection from this list is mandatory.' },
  'fld-format-as': { title: 'Formatted Inputs', body: 'Applies an input format (phone, email, currency, etc.) to guide and validate entry.' },
  'fld-format-mask': { title: 'Mask', body: 'A character mask that shapes input as you type, e.g. phone or IC number formats.' },
  'fld-off-autocomplete': { title: 'Disable autocomplete', body: 'Turns off the browser\'s autocomplete suggestions for this field.' },
  'fld-prefix': { title: 'Prefix', body: 'Fixed text shown before the input value (e.g. RM, +60).' },
  'fld-suffix': { title: 'Suffix', body: 'Fixed text shown after the input value (e.g. %, kg).' },
  'fld-options-list-values': { title: 'Options list values', body: 'The selectable options, separated by double semi-colons (;;).' },
  'options-quick-list': { title: 'Quick list', body: 'Frequently used values you can add to the options list quickly.' },
  'fld-boolean-label-true': { title: 'Label if TRUE', body: 'The label shown when the boolean is true (e.g. "Active").' },
  'fld-boolean-label-false': { title: 'Label if FALSE', body: 'The label shown when the boolean is false (e.g. "Inactive").' },

  // ============ Menu management ============
  'app-app-menu_orientation_top': { title: 'Menu orientation', body: 'Choose where the main navigation sits in the generated app.' },
  'app-app-menu_orientation_side': { title: 'Side menu (vertical)', body: 'Navigation lives in a vertical sidebar — best for apps with many modules.' },
  'app-menu_at_homepage': { title: 'Menu at Homepage', body: 'Whether the navigation menu is shown on the homepage.' },
  'app-tables-per-row': { title: 'Tables per row', body: 'How many table panels are shown per row on the homepage grid.' },
  'app-panel-height': { title: 'Panel height (px)', body: 'Height of each table panel on the homepage in pixels.' },
  'app-extra_wide_yes': { title: 'First table extra wide', body: 'The first table on the homepage spans wider than the rest — good for the most-used module.' },
  'app-extra-wide_no': { title: 'Uniform panels', body: 'All homepage table panels keep the same width.' },

  // ============ Theme ============
  'app-theme-preset': { title: 'Theme preset', body: 'A ready-made colour scheme for the generated admin panel. Switch any time — it only changes colours, not behaviour.' },
  'app-theme-custom-color': { title: 'Primary color', body: 'Pick your own primary colour. Buttons, links and highlights are derived from it.' },
  'app-theme-custom-name': { title: 'Theme name', body: 'Name your custom theme so you can reuse it across projects.' },

  // ============ Dashboard Builder ============
  'kiosk-enabled': { title: 'Kiosk display mode', body: 'Turns the dashboard into a full-screen wall display that auto-rotates pages — for TVs and office screens.' },
  'kiosk-rotate-seconds': { title: 'Rotate every', body: 'Seconds between dashboard page rotations in kiosk mode.' },
  'kiosk-page-size': { title: 'Widgets per page', body: 'How many widgets fill each kiosk page before rotating.' },
  'widget-id': { title: 'Widget ID', body: 'Internal identifier of this widget. Auto-assigned.' },
  'widget-advanced-query': { title: 'Advanced query', body: 'Override the widget\'s data source with a custom SQL query. Advanced — leave empty for the standard aggregation.' },
  'widget-title': { title: 'Widget title', body: 'The heading shown on the widget card.' },
  'widget-type': { title: 'Widget type', body: 'What the widget shows: a stat number, latest-records table, or one of the chart types (bar, line, area, pie, doughnut, polar, radar, scatter, bubble, combo).' },
  'widget-target-table': { title: 'Source Table', body: 'The table this widget reads its data from.' },
  'widget-aggregate-type': { title: 'Calculation (Aggregate)', body: 'How the numbers are computed: count, sum, average, min or max.' },
  'widget-width-span': { title: 'Display Width', body: 'How many grid columns the widget occupies (1 = narrow, full width = 12).' },
  'widget-color': { title: 'Theme Color', body: 'Accent colour used by the widget\'s chart bars/lines/segments.' },
  'widget-icon': { title: 'Icon (Heroicon)', body: 'Icon shown on stat widgets.' },
  'widget-chart-label': { title: 'Group Data By', body: 'The column whose values become the chart\'s categories/labels (e.g. group sales by month or status).' },
  'widget-target-field': { title: 'Target Column (SUM/AVG)', body: 'The numeric column the aggregate is computed over.' },
  'widget-series-field': { title: 'Second Numeric Column (Y-Axis)', body: 'For combo charts: the second numeric column plotted on the line series.' },
  'widget-series-agg': { title: 'Line Series Calc', body: 'The aggregate applied to the second series.' },
  'widget-size-field': { title: 'Size field (bubble)', body: 'For bubble charts: the column that controls bubble size.' },
  'widget-filter-field': { title: 'Filter field', body: 'Restrict the widget\'s data with a filter on this column.' },
  'widget-filter-operator': { title: 'Operator', body: 'The filter comparison: equals, greater than, contains, etc.' },
  'widget-filter-value': { title: 'Value', body: 'The value the filter compares against.' },
  'widget-timeframe': { title: 'Timeframe', body: 'Limits the data window: last 7/30/90 days, this month, this year, etc.' },
  'widget-refresh-mode': { title: 'Live Updates', body: 'How the widget refreshes: static (never), poll (every N seconds), or live (pushed via the real-time module).' },
  'widget-refresh-interval': { title: 'Refresh Every (seconds)', body: 'Polling interval when the refresh mode is poll.' },

  // ============ Architecture ============
  'fg-tenant-table': { title: 'Tenant table', body: 'The table representing tenants (companies, schools, clients). Every tenant-scoped table links back to it.' },
  'btn-configure-tenancy': { title: 'Configure tenancy', body: 'Opens the multi-tenancy configuration: choose the tenant table and which tables are tenant-scoped.' },
  'btn-edit-tenancy': { title: 'Edit tenancy', body: 'Change the tenancy configuration for this project.' },

  // ============ Security & technical (rebuilt 2026-10-01) ============
  'app-admins_group_access': { title: 'Admins group access', body: 'Creates an "admins" Shield role holding every permission. Any user assigned to it gets full admin-area access — no per-user permission work needed.' },
  'app-allow_server_status': { title: 'Server status page', body: 'Adds a read-only /admin/server-status page: PHP version and limits, required extensions, Laravel environment, disk and memory headroom, queue backlog. Admins only.' },
  'app-allow_pwa_install': { title: 'PWA install', body: 'Generates a web manifest + service worker so the admin panel installs like a native app on phones and desktops, using your theme color and app icons.' },
  'fixzy-check-updates': { title: 'Check for updates', body: 'On startup, SysMaker checks GitHub for a newer release and shows a toast when one is available.' },
  'fixzy-show-begin-box': { title: 'Show beginner box', body: 'Shows the "How do you want to begin?" box on startup so you can pick New Project, Import SQL, or go straight to work.' },
  'fixzy-lock-core-components': { title: 'Lock core components', body: 'Prevents editing system-critical tables and fields that the generated app depends on.' },
  'fixzy-font-size-small': { title: 'Small UI font', body: 'Smaller font size for the SysMaker interface itself.' },
  'fixzy-font-size-medium': { title: 'Medium UI font', body: 'Default font size for the SysMaker interface.' },
  'fixzy-font-size-large': { title: 'Large UI font', body: 'Larger font size for the SysMaker interface.' },
  'fixzy-doc-root': { title: 'Document root', body: 'The web server document root path for deployment output.' },
  'fixzy-base-url': { title: 'Base URL', body: 'Default URL pre-filled for new projects (e.g. http://localhost). Each project can change it later.' },
  'fixzy-field-default-type': { title: 'Default data type', body: 'Data type pre-selected when you add a new field.' },
  'fixzy-field-default-length': { title: 'Default length', body: 'Length pre-filled for new text fields.' },
  'fixzy-table-allow-csv': { title: 'Default CSV allowed', body: 'New tables have CSV import/export enabled by default.' },
  'fixzy-table-dv-separate-page': { title: 'Default separate page form', body: 'New tables open the Record Form on a separate page by default.' },
  'fixzy-table-hide-save-as-copy': { title: 'Default hide Save As Copy', body: 'New tables hide the "Save As Copy" button by default.' },
  'fixzy-table-allow-add-from-homepage': { title: 'Default add from homepage', body: 'New tables allow adding records from the homepage by default.' },
  'fixzy-table-show-record-count': { title: 'Show record count', body: 'Shows the total record count on table panels.' },
  'fixzy-global-tv-template': { title: 'Global Table List template', body: 'Default list template applied to all tables unless overridden.' },
  'fixzy-global-card-columns': { title: 'Global card columns', body: 'Default cards-per-row for all tables.' },
  'fixzy-global-form-style': { title: 'Global form style', body: 'Default form style applied to all tables.' },
  'fixzy-global-form-columns': { title: 'Global form columns', body: 'Default number of form columns for all tables.' },
  'fixzy-global-child-tv-template': { title: 'Global child template', body: 'Default list template for child tables in parent-child views.' },
  'fixzy-global-child-card-columns': { title: 'Global child card columns', body: 'Default cards-per-row for child tables.' },
  'fixzy-global-child-form-style': { title: 'Global child form style', body: 'Default form style for child tables.' },
  'fixzy-apply-view': { title: 'Apply to views', body: 'Applies the global list settings to all table views.' },
  'fixzy-apply-form': { title: 'Apply to forms', body: 'Applies the global form settings to all table forms.' },
  'fixzy-apply-child': { title: 'Apply to children', body: 'Applies the global settings to all child table views/forms.' },
  'fixzy-max-entries': { title: 'Default records per page', body: 'Number of records shown per page in newly generated tables (10-500).' },
  'auto-default-select': { title: 'Auto default', body: 'Automatically selects sensible defaults for dependent options.' },
  'new-project-name': { title: 'Project name', body: 'The name of your new project. Used for the project folder and default app title.' },
  'cqb-advanced-mode-toggle': { title: 'Advanced mode', body: 'Switches the query builder to advanced mode with raw expression editing.' },
  'cqb-calc-function': { title: 'Calc function', body: 'The aggregate/function applied in the calculation builder.' },
  'cqb-calc-field': { title: 'Calc field', body: 'The field the calculation function is applied to.' },
  'cqb-adv-function': { title: 'Advanced function', body: 'Function used in the advanced expression.' },
  'cqb-distinct-toggle': { title: 'Distinct', body: 'Counts only distinct (unique) values.' },
  'cqb-expr-field1': { title: 'Expression field 1', body: 'First field in the expression.' },
  'cqb-expr-operator': { title: 'Expression operator', body: 'Operator combining the two fields (+, -, *, /, etc.).' },
  'cqb-expr-field2': { title: 'Expression field 2', body: 'Second field in the expression.' },
  'custom-menu-item-id': { title: 'Custom menu item ID', body: 'Internal ID of the custom menu item.' },
  'custom-menu-label-input': { title: 'Menu label', body: 'The label shown in the navigation menu for this custom item.' },
  'custom-menu-url-input': { title: 'Menu URL', body: 'The URL or route this custom menu item links to.' },
  'custom-menu-url-table-select': { title: 'Link to table', body: 'Alternatively, link the menu item directly to a table\'s list view.' },
  'qh-table-select': { title: 'Quick hook table', body: 'Pick the table this quick hook applies to.' },
  'qh-preview-area': { title: 'Hook preview', body: 'Preview of the generated hook code. Read-only.' },
  'wizard-existing-table': { title: 'Existing table', body: 'Base the new module on an existing table instead of creating a new one.' },
  'wizard-new-table-name': { title: 'New table name', body: 'Name for the new table created by the wizard.' },

  // ============ Hooks ============
  'app-hook-logic': { title: 'Project hook logic', body: 'Custom logic that runs on global project events. For advanced integrations — most apps leave this empty.' }
};
