<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Imports;

use App\Models\Aset;

use Filament\Actions\Imports\ImportColumn;
use Filament\Actions\Imports\Importer;
use Filament\Actions\Imports\Models\Import;
use Illuminate\Support\Number;
use Filament\Forms\Components\Checkbox;

/**
 * Generated importer for Aset rows from CSV/XLSX.
 */
class AsetImporter extends Importer
{
    protected static ?string $model = Aset::class;

    /**
     * Mappable import columns with type casts and rules.
     * @return  array  ImportColumn definitions.
     */
    public static function getColumns(): array
    {
        return [
            ImportColumn::make('id')
                ->label('Id')
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('Id'),

            ImportColumn::make('nama_aset')
                ->label('Nama Aset')
                ->requiredMapping()
                ->ignoreBlankState()
                ->rules(['required', 'max:150'])
                ->examples(['Sample Nama Aset 1', 'Sample Nama Aset 2'])
                ->exampleHeader('Nama Aset'),

            ImportColumn::make('created_by')
                ->label('Created By')
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('Created By'),

            ImportColumn::make('updated_by')
                ->label('Updated By')
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('Updated By'),
        ];
    }

    /**
     * Resolve which record this imported row maps to (generated custom logic).
     * @return  ?Aset  Resolved record instance.
     */
    public function resolveRecord(): ?Aset
    {
    return new Aset();
    }

    /**
     * Notification body shown when the import finishes.
     *
     * @param  Import  $import  The completed import job.
     * @return  string  Human-readable completion summary.
     */
    public static function getCompletedNotificationBody(Import $import): string
    {
        $body = 'Your Aset import has completed and ' . Number::format($import->successful_rows) . ' ' . str('row')->plural($import->successful_rows) . ' imported.';

        if ($failedRowsCount = $import->getFailedRowsCount()) {
            $body .= ' ' . Number::format($failedRowsCount) . ' ' . str('row')->plural($failedRowsCount) . ' failed to import.';
        }

        return $body;
    }
    
    /**
     * Extra options form shown before importing (dry run / update existing).
     * @return  array  Form component definitions.
     */
    public static function getOptionsFormComponents(): array
    {
        return [
            Checkbox::make('updateExisting')
                ->label('Update existing records'),
        ];
    }

}
