<?php

namespace App\Filament\Auth;

use Filament\Auth\Http\Responses\Contracts\LoginResponse;
use Filament\Auth\Pages\Login;
use Filament\Forms\Components\TextInput;
use Filament\Notifications\Notification;
use Filament\Schemas\Schema;
use Illuminate\Validation\ValidationException;

/**
 * Combined login page generated by Fixzy SysMaker.
 *
 * Includes only the features enabled in the project settings:
 *   - captcha: built-in arithmetic human check (no third-party service)
 *   - LDAP:    directory authentication via App\Services\LdapAuthenticator
 *   - Google SSO button (handled by routes; shown via panel render hook)
 */
class FixzyLogin extends Login
{
    public function form(Schema $schema): Schema
    {
        $components = [
            $this->getEmailFormComponent(),
            $this->getPasswordFormComponent(),
            $this->getRememberFormComponent(),
        ];

        

        
        // Google reCAPTCHA v2: the visible "I'm not a robot" widget is
        // rendered by the panel render hook (fixzy-recaptcha-widget view).
        // Its callback pushes the token into this field's Livewire state,
        // and the token is verified server-side here.
        $components[] = \Filament\Forms\Components\Hidden::make('g-recaptcha-response')
            ->required()
            ->rule(function (string $attribute, $value): bool {
                return \App\Services\RecaptchaService::verify(
                    $value ? (string) $value : null,
                    request()->ip()
                );
            }, 'Human verification failed — please complete the reCAPTCHA and try again.');
        

        return $schema->components($components);
    }

    
}
