<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\Jobs;

use App\Filament\Resources\Jobs\Pages\CreateJob;
use App\Filament\Resources\Jobs\Pages\EditJob;
use App\Filament\Resources\Jobs\Pages\ListJobs;
use App\Filament\Resources\Jobs\Schemas\JobForm;
use App\Filament\Resources\Jobs\Tables\JobsTable;
use App\Models\Job;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;

use Filament\Actions\Action;
use App\Filament\Actions\PrintAction;

use App\Filament\Imports\JobImporter;
use Filament\Actions\ImportAction;
use App\Filament\Exports\JobExporter;
use Filament\Actions\ExportAction;

use App\Filament\Resources\Jobs\RelationManagers\JobTaskRelationManager;
use App\Filament\RelationManagers\AuditsRelationManager;

/**
 * Generated Filament resource for the Job model.
 */
class JobResource extends Resource
{
    protected static ?string $model = Job::class;
    
    

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    
    
    

    /**
     * Delegate the form definition to the generated form schema class.
     *
     * @param  Schema  $schema  The resource form schema.
     * @return  Schema  The configured schema.
     */
    public static function form(Schema $schema): Schema
    {
        return JobForm::configure($schema);
    }

    /**
     * Delegate the table definition and add import/export/print header actions.
     *
     * @param  Table  $table  The resource table instance.
     * @return  Table  The configured table.
     */
    public static function table(Table $table): Table
    {
        return JobsTable::configure($table)
		        ->headerActions([
ImportAction::make()->importer(JobImporter::class),
ExportAction::make()->exporter(JobExporter::class)
                /*->enableVisibleTableColumnsByDefault()*/,
			Action::make('print')
                    ->label('Print')
                    ->icon('heroicon-o-printer')
                    ->color('gray')
                    ->url(fn (): string => request()->fullUrlWithQuery(['print' => 1]))
                    ->openUrlInNewTab(),
        ]);
    }

    /**
     * Relation managers shown on the resource, gated by the current user's permissions.
     * @return  array  Relation manager class names.
     */
    public static function getRelations(): array
    {
        $relations = [
                        JobTaskRelationManager::class,
        ];
		

    // Only add AuditsRelationManager if the user is allowed to view it
    
        if (auth()->check() && auth()->user()->can('view_any_audit')) {
            $relations[] = AuditsRelationManager::class;
        }
	
	return $relations;
    }

    /**
     * Route bindings for the resource's list, create and edit pages.
     * @return  array  Page name to route mapping.
     */
    public static function getPages(): array
    {
        return [
            'index' => ListJobs::route('/'),
            'create' => CreateJob::route('/create'),
            'edit' => EditJob::route('/{record}/edit'),
        ];
    }
	
    // 1. Set the URL
    protected static ?string $slug = 'jobs';

    // 2. Set the label for a single record
    /**
     * Singular label for the model.
     * @return  string  Singular model label.
     */
    public static function getModelLabel(): string
    {
        return 'Job';
    }

    // 3. Set the label for multiple records (main resource page title)
    /**
     * Plural label used in the navigation menu.
     * @return  string  Plural model label.
     */
    public static function getPluralModelLabel(): string
    {
        return 'Jobs';
    }
	
    
    public static function getNavigationGroup(): string
    {
        return 'Work Orders';
    }

    
    public static function getNavigationSort(): int
    {
        return 0;
    }
}
