<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\TvVertical2;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\TvVertical2>
 */
class TvVertical2Factory extends Factory
{
    protected $model = TvVertical2::class;

    public function definition(): array
    {
        return [
            'nama_fakulti' => fake()->name(),
        ];
    }
}
