<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Resources\Induks\RelationManagers;

use App\Filament\Resources\AnakKads\AnakKadResource;
use Filament\Actions\CreateAction;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Columns\Layout\Panel;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

/**
 * Generated relation manager for AnakKad children of the parent record.
 */
class AnakKadRelationManager extends RelationManager
{
    protected static string $relationship = 'anakKads';
    
    protected static ?string $title = 'Cards';
    
    
    protected static ?string $relatedResource = AnakKadResource::class;

    /**
     * Child record table with a create header action.
     *
     * @param  Table  $table  The relation table instance.
     * @return  Table  The configured table.
     */
    public function table(Table $table): Table
    {
        return $table
            ->headerActions([
                CreateAction::make(),
            ])
            ->columns([
                Panel::make([
                    TextColumn::make('id')
                    ->label('Id')
                    ->sortable()
                    ->limit(50, end: ' (more)')
                    ->searchable()
                    ->toggleable()
                    ->numeric(),
                    TextColumn::make('tajuk_kad')
                    ->label('Card Title')
                    ->sortable()
                    ->limit(50, end: ' (more)')
                    ->searchable()
                    ->toggleable(),
                    TextColumn::make('induk.nama_induk')
                    ->label('Parent')
                    ->sortable()
                    ->limit(50, end: ' (more)')
                    ->searchable()
                    ->toggleable()
                    ->numeric()
                ])
            ])
            ->contentGrid(['md' => 2, 'xl' => 3]);
    }
}
