<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;



/**
 * Generated Eloquent model for the aduan table.
 */
class Complaint extends Model 
{
	
    
    use SoftDeletes;
    
    
    /**
     *
     * @var string
     */
    protected $table = 'aduan';
    /**
     *
     * @var string
     */
    protected $primaryKey = 'id';
    /**
     *
     * @var array<int, string>
     */
    protected $fillable = [
        
        'txt_plain',
        'txt_email',
        'txt_area',
        'txt_rich',
        'bool_urgent',
        'opt_category',
        'opt_channels',
        'opt_priority',
        'lk_watak',
        'lk_watak_radio',
        'rep_notes',
        'num_amount',
        'dt_event',
        'dt_report',
        'aduan_status',
        'img_proof',
        'doc_form',
        'files_extra',
        'map_place',
        'vid_evidence',
        'internal_note',
        'public_reference'
    
    ];
    

    protected function casts(): array
    {
        return [
            'bool_urgent' => 'boolean',
            'opt_channels' => 'array',
            'rep_notes' => 'array',
            'files_extra' => 'array',
        ];
    }
    


    public function character()
    {
        return $this->belongsTo(Character::class, 'lk_watak', 'id');
    }
    public function characterLkWatakRadio()
    {
        return $this->belongsTo(Character::class, 'lk_watak_radio', 'id');
    }	




    public function getCleanYoutubeUrl(string $fieldName): string
    {
        $url = $this->{$fieldName};
        if (blank($url)) {
            return '';
        }

        preg_match('/(?:v=|\/v\/|watch\?v=|youtu\.be\/|embed\/)([a-zA-Z0-9_-]{11})/', $url, $matches);

        if (isset($matches[1])) {
            return 'https://www.youtube.com/embed/' . $matches[1];
        }

        return $url;
    }

}
