<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\Leads\RelationManagers;

use App\Filament\Resources\Activities\ActivityResource;
use Filament\Actions\CreateAction;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Table;

/**
 * Generated relation manager for Activity children of the parent record.
 */
class ActivityRelationManager extends RelationManager
{
    protected static string $relationship = 'activities';
    
    
    protected static ?string $relatedResource = ActivityResource::class;

    /**
     * Child record table with a create header action.
     *
     * @param  Table  $table  The relation table instance.
     * @return  Table  The configured table.
     */
    public function table(Table $table): Table
    {
        return $table
            ->headerActions([
                CreateAction::make(),
            ]);
    }
}
