<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace App\Filament\Resources\ProfilPelajars\Schemas;

use App\Filament\Resources\Pelajars\PelajarResource;

use Illuminate\Contracts\View\View;
use Filament\Schemas\Schema;
use Filament\Pages\Page;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Section;
use Filament\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;

/**
 * Generated form schema fragment for this table's fields.
 */
class ProfilPelajarForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make("Detail View")
                ->columns(fn (Page $livewire) => $livewire->gridColumns)
    ->headerActions([
        Action::make('1 Kolum')
            ->icon('heroicon-o-queue-list')
            ->iconButton()
            ->color('gray')
            ->tooltip('Display 1 column')
            ->action(fn (Page $livewire) => $livewire->gridColumns = 1),

        Action::make('2 Kolum')
            ->icon('heroicon-o-view-columns')
            ->iconButton()
            ->color('gray')
            ->tooltip('Display 2 column')
            ->action(fn (Page $livewire) => $livewire->gridColumns = 2),

        Action::make('3 Kolum')
            ->icon('heroicon-o-table-cells')
            ->iconButton()
            ->color('gray')
            ->tooltip('Display 3 column')
            ->action(fn (Page $livewire) => $livewire->gridColumns = 3),
    ])
                ->schema([
				TextInput::make('id')
    ->integer()
    ->readOnly()
    ->maxLength(11)
    ->label('Id')
    ->trim(),
                Select::make('pelajar_id')
    ->required()->markAsRequired()
    ->unique(ignoreRecord: true)
    ->label('Pelajar Id')
    ->searchable()
    ->preload()
    ->relationship('pelajar', 'nama_penuh')
    ->live()
    ->suffixActions([
    Action::make('view_pelajar')
        ->icon('heroicon-o-eye')
        ->modalContent(fn (Get $get): ?View => $get('pelajar_id') ? view('filament.components.modal-iframe', ['src' => PelajarResource::getUrl('edit', ['record' => $get('pelajar_id')]) . '?iframe=1']) : null)
        ->modalWidth('6xl')
        ->modalSubmitAction(false)
        ->hidden(fn (Get $get): bool => !$get('pelajar_id')),
    Action::make('create_pelajar')
        ->icon('heroicon-o-plus')
        ->modalContent(fn (): View => view('filament.components.modal-iframe', ['src' => PelajarResource::getUrl('create') . '?iframe=1']))
        ->modalWidth('6xl')
        ->modalSubmitAction(false),
])
    ,
                TextInput::make('alamat')
    ->label('Alamat')
    ->trim(),
                TextInput::make('no_telefon')
    ->maxLength(20)
    ->default('NULL')
    ->label('No Telefon')
    ->trim(),
                TextInput::make('tarikh_lahir')
    ->default('NULL')
    ->label('Tarikh Lahir')
    ->trim(),
                Select::make('info_kecemasan')
    ->default('NULL')
    ->label('Info Kecemasan')
    ->options(['Primary' => 'Primary', 'Secondary' => 'Secondary', 'Diploma' => 'Diploma', 'Degree' => 'Degree', 'Masters' => 'Masters', 'PhD' => 'Ph D'])
    ,
                TextInput::make('created_at')
    ->label('Created At')
    ->trim(),
                TextInput::make('updated_at')
    ->label('Updated At')
    ->trim(),
                TextInput::make('deleted_at')
    ->label('Deleted At')
    ->trim(),
                ])
                ->columnSpanFull(),
        ]);
    }
}