<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

/**
 * Forces JSON content negotiation on the generated REST API
 * (Fixzy SysMaker). Ensures auth failures answer 401 JSON instead
 * of redirecting to a login route that may not exist.
 */
class ApiJsonRequest
{
    /**
     * Force a JSON Accept header on api/* requests so failures answer JSON, never a login redirect.
     *
     * @param  Request  $request  Incoming request.
     * @param  Closure  $next  Next middleware handler.
     * @return  mixed  The downstream response.
     */
    public function handle(Request $request, Closure $next)
    {
        if ($request->is('api/*')) {
            $request->headers->set('Accept', 'application/json');
        }

        return $next($request);
    }
}
