<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Widgets;

/**
 * Report widget "Enrolments by Grade" (Fixzy SysMaker generated code).
 * Compiled from the Dashboard Builder — edit in Fixzy SysMaker, not here.
 */
class Report_w5 extends BaseReportChart
{
    /** @var array<string, mixed> */
    protected static array $cfg = [
        'id' => "w5",
        'title' => "Enrolments by Grade",
        'type' => "chart_bar",
        'table' => "pendaftaran_kursus",
        'model' => "App\\Models\\CourseRegistration",
        'width' => "1",
        'color' => "primary",
        'icon' => "heroicon-o-chart-bar",
        'aggregate' => "count",
        'label_field' => "gred",
        'value_field' => "",
        'series_field' => "",
        'size_field' => "",
        'series_aggregate' => "sum",
        'filter_field' => "",
        'filter_operator' => "",
        'filter_value' => "",
        'timeframe' => "all",
        'refresh_mode' => "poll",
        'refresh_interval' => "15",
        'advanced' => null,
    ];

}
