<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Widgets;

/**
 * Report widget "Registrations Over Time" (Fixzy SysMaker generated code).
 * Compiled from the Dashboard Builder — edit in Fixzy SysMaker, not here.
 */
class Report_w8 extends BaseReportChart
{
    /** @var array<string, mixed> */
    protected static array $cfg = [
        'id' => "w8",
        'title' => "Registrations Over Time",
        'type' => "chart_line",
        'table' => "pelajar",
        'model' => "App\\Models\\Student",
        'width' => "1",
        'color' => "primary",
        'icon' => "heroicon-o-chart-bar",
        'aggregate' => "count",
        'label_field' => "tarikh_daftar",
        'value_field' => "",
        'series_field' => "",
        'size_field' => "",
        'series_aggregate' => "sum",
        'filter_field' => "",
        'filter_operator' => "",
        'filter_value' => "",
        'timeframe' => "all",
        'refresh_mode' => "poll",
        'refresh_interval' => "15",
        'advanced' => null,
    ];

}
