<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Widgets;

/**
 * Report widget "Total Invoices" (Fixzy SysMaker generated code).
 * Compiled from the Dashboard Builder — edit in Fixzy SysMaker, not here.
 */
class Report_w3 extends BaseReportStats
{
    /** @var array<string, mixed> */
    protected static array $cfg = [
        'id' => "w3",
        'title' => "Total Invoices",
        'type' => "stats",
        'table' => "invoice",
        'model' => "App\\Models\\Invoice",
        'width' => "1",
        'color' => "warning",
        'icon' => "heroicon-o-receipt-percent",
        'aggregate' => "count",
        'label_field' => "",
        'value_field' => "",
        'series_field' => "",
        'size_field' => "",
        'series_aggregate' => "sum",
        'filter_field' => "",
        'filter_operator' => "",
        'filter_value' => "",
        'timeframe' => "all",
        'refresh_mode' => "poll",
        'refresh_interval' => "15",
        'advanced' => null,
    ];

}
