<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Widgets;

/**
 * Report widget "Recent Invoices" (Fixzy SysMaker generated code).
 * Compiled from the Dashboard Builder — edit in Fixzy SysMaker, not here.
 */
class Report_w15 extends BaseReportTable
{
    /** @var array<string, mixed> */
    protected static array $cfg = [
        'id' => "w15",
        'title' => "Recent Invoices",
        'type' => "table_latest",
        'table' => "invoice",
        'model' => "App\\Models\\Invoice",
        'width' => "1",
        'color' => "success",
        'icon' => "heroicon-o-chart-bar",
        'aggregate' => "count",
        'label_field' => "",
        'value_field' => "",
        'series_field' => "",
        'size_field' => "",
        'series_aggregate' => "sum",
        'filter_field' => "",
        'filter_operator' => "",
        'filter_value' => "",
        'timeframe' => "all",
        'refresh_mode' => "poll",
        'refresh_interval' => "15",
        'advanced' => null,
    ];

}
