<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Widgets;

/**
 * Report widget "Course Credit Profile" (Fixzy SysMaker generated code).
 * Compiled from the Dashboard Builder — edit in Fixzy SysMaker, not here.
 */
class Report_w11 extends BaseReportChart
{
    /** @var array<string, mixed> */
    protected static array $cfg = [
        'id' => "w11",
        'title' => "Course Credit Profile",
        'type' => "chart_radar",
        'table' => "kursus",
        'model' => "App\\Models\\Course",
        'width' => "1",
        'color' => "danger",
        'icon' => "heroicon-o-chart-bar",
        'aggregate' => "sum",
        'label_field' => "nama_kursus",
        'value_field' => "jam_kredit",
        'series_field' => "",
        'size_field' => "",
        'series_aggregate' => "sum",
        'filter_field' => "",
        'filter_operator' => "",
        'filter_value' => "",
        'timeframe' => "all",
        'refresh_mode' => "poll",
        'refresh_interval' => "15",
        'advanced' => null,
    ];

}
