<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Imports;

use App\Models\Character;

use Filament\Actions\Imports\ImportColumn;
use Filament\Actions\Imports\Importer;
use Filament\Actions\Imports\Models\Import;
use Illuminate\Support\Number;
use Filament\Forms\Components\Checkbox;

/**
 * Generated importer for Characters rows from CSV/XLSX.
 */
class CharacterImporter extends Importer
{
    protected static ?string $model = Character::class;

    /**
     * Mappable import columns with type casts and rules.
     * @return  array  ImportColumn definitions.
     */
    public static function getColumns(): array
    {
        return [
            ImportColumn::make('id')
                ->label('ID')
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('ID'),

            ImportColumn::make('nama_watak')
                ->label('Character Name')
                ->requiredMapping()
                ->ignoreBlankState()
                ->rules(['required', 'max:255'])
                ->examples(['Sample Character Name 1', 'Sample Character Name 2'])
                ->exampleHeader('Character Name'),
        ];
    }

    /**
     * Resolve which record this imported row maps to (generated custom logic).
     * @return  ?Character  Resolved record instance.
     */
    public function resolveRecord(): ?Character
    {
    return new Character();
    }

    /**
     * Notification body shown when the import finishes.
     *
     * @param  Import  $import  The completed import job.
     * @return  string  Human-readable completion summary.
     */
    public static function getCompletedNotificationBody(Import $import): string
    {
        $body = 'Your Characters import has completed and ' . Number::format($import->successful_rows) . ' ' . str('row')->plural($import->successful_rows) . ' imported.';

        if ($failedRowsCount = $import->getFailedRowsCount()) {
            $body .= ' ' . Number::format($failedRowsCount) . ' ' . str('row')->plural($failedRowsCount) . ' failed to import.';
        }

        return $body;
    }
    
    /**
     * Extra options form shown before importing (dry run / update existing).
     * @return  array  Form component definitions.
     */
    public static function getOptionsFormComponents(): array
    {
        return [
            Checkbox::make('updateExisting')
                ->label('Update existing records'),
        ];
    }

}
