<x-filament-panels::page>
<div style="display:flex; flex-wrap:wrap; margin:-8px;">
        <a href="/admin/students" style="box-sizing:border-box; width:calc(50.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1.15rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Students</a>
        <a href="/admin/studentprofile" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Student Profiles</a>
        <a href="/admin/courses" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Courses</a>
        <a href="/admin/examresults" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Exam Results</a>
        <a href="/admin/courseregistration" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Registrations</a>
        <a href="/admin/registrationapproval" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Approvals</a>
        <a href="/admin/invoices" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Invoices</a>
        <a href="/admin/faculties" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Faculties</a>
        <a href="/admin/studentdocuments" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Documents</a>
        <a href="/admin/users" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Users</a>
</div>
</x-filament-panels::page>
