<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Exports;

use App\Models\Pelanggan;
use Filament\Actions\Exports\ExportColumn;
use Filament\Actions\Exports\Exporter;
use Filament\Actions\Exports\Models\Export;
use Illuminate\Support\Number;

/**
 * Generated exporter for Pelanggan records (CSV/XLSX).
 */
class PelangganExporter extends Exporter
{
    protected static ?string $model = Pelanggan::class;

    /**
     * Columns included in the export.
     * @return  array  Export column definitions.
     */
    public static function getColumns(): array
    {
        return [
                        ExportColumn::make('id')->limit(50)->label('Id'),
            ExportColumn::make('nama_pelanggan')->limit(50)->label('Nama Pelanggan'),
            ExportColumn::make('emel')->limit(50)->label('Emel'),
        ];
    }

    /**
     * Notification body shown when the export finishes.
     *
     * @param  Export  $export  The completed export job.
     * @return  string  Human-readable completion summary.
     */
    public static function getCompletedNotificationBody(Export $export): string
    {
        $body = 'Your Pelanggan export has completed and ' . Number::format($export->successful_rows) . ' ' . str('row')->plural($export->successful_rows) . ' exported.';

        if ($failedRowsCount = $export->getFailedRowsCount()) {
            $body .= ' ' . Number::format($failedRowsCount) . ' ' . str('row')->plural($failedRowsCount) . ' failed to export.';
        }

        return $body;
    }
}
