<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;



/**
 * Generated Eloquent model for the induk table.
 */
class Induk extends Model 
{
	
    
    use SoftDeletes;
    
    
    /**
     *
     * @var string
     */
    protected $table = 'induk';
    /**
     *
     * @var string
     */
    protected $primaryKey = 'id';
    /**
     *
     * @var array<int, string>
     */
    protected $fillable = [
        
        'nama_induk',
        'meta_decimal',
        'meta_date',
        'lk_watak'
    
    ];
    
    


    public function anaks()
    {
        return $this->hasMany(Anak::class, 'fk_induk', 'id');
    }
    public function anakKads()
    {
        return $this->hasMany(AnakKad::class, 'fk_induk', 'id');
    }
    public function indukExtra()
    {
        return $this->hasOne(IndukExtra::class, 'fk_induk', 'id');
    }
    public function character()
    {
        return $this->belongsTo(Character::class, 'lk_watak', 'id');
    }	




}
