<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\LaporanBulanans;

use App\Filament\Resources\LaporanBulanans\Pages\CreateLaporanBulanan;
use App\Filament\Resources\LaporanBulanans\Pages\EditLaporanBulanan;
use App\Filament\Resources\LaporanBulanans\Pages\ListLaporanBulanans;
use App\Filament\Resources\LaporanBulanans\Schemas\LaporanBulananForm;
use App\Filament\Resources\LaporanBulanans\Tables\LaporanBulanansTable;
use App\Models\LaporanBulanan;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;

use Filament\Actions\Action;
use App\Filament\Actions\PrintAction;

use App\Filament\Imports\LaporanBulananImporter;
use Filament\Actions\ImportAction;
use App\Filament\Exports\LaporanBulananExporter;
use Filament\Actions\ExportAction;


use App\Filament\RelationManagers\AuditsRelationManager;

/**
 * Generated Filament resource for the LaporanBulanan model.
 */
class LaporanBulananResource extends Resource
{
    protected static ?string $model = LaporanBulanan::class;
    
    

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    
    
    

    /**
     * Delegate the form definition to the generated form schema class.
     *
     * @param  Schema  $schema  The resource form schema.
     * @return  Schema  The configured schema.
     */
    public static function form(Schema $schema): Schema
    {
        return LaporanBulananForm::configure($schema);
    }

    /**
     * Delegate the table definition and add import/export/print header actions.
     *
     * @param  Table  $table  The resource table instance.
     * @return  Table  The configured table.
     */
    public static function table(Table $table): Table
    {
        return LaporanBulanansTable::configure($table)
		        ->headerActions([
ImportAction::make()->importer(LaporanBulananImporter::class),
ExportAction::make()->exporter(LaporanBulananExporter::class)
                /*->enableVisibleTableColumnsByDefault()*/,
			Action::make('print')
                    ->label('Print')
                    ->icon('heroicon-o-printer')
                    ->color('gray')
                    ->url(fn (): string => request()->fullUrlWithQuery(['print' => 1]))
                    ->openUrlInNewTab(),
        ]);
    }

    /**
     * Relation managers shown on the resource, gated by the current user's permissions.
     * @return  array  Relation manager class names.
     */
    public static function getRelations(): array
    {
        $relations = [
            
        ];
		

    // Only add AuditsRelationManager if the user is allowed to view it
    
        if (auth()->check() && auth()->user()->can('view_any_audit')) {
            $relations[] = AuditsRelationManager::class;
        }
	
	return $relations;
    }

    /**
     * Route bindings for the resource's list, create and edit pages.
     * @return  array  Page name to route mapping.
     */
    public static function getPages(): array
    {
        return [
            'index' => ListLaporanBulanans::route('/'),
            'create' => CreateLaporanBulanan::route('/create'),
            'edit' => EditLaporanBulanan::route('/{record}/edit'),
        ];
    }
	
    // 1. Set the URL
    protected static ?string $slug = 'laporanbulanan';

    // 2. Set the label for a single record
    /**
     * Singular label for the model.
     * @return  string  Singular model label.
     */
    public static function getModelLabel(): string
    {
        return 'LaporanBulanan';
    }

    // 3. Set the label for multiple records (main resource page title)
    /**
     * Plural label used in the navigation menu.
     * @return  string  Plural model label.
     */
    public static function getPluralModelLabel(): string
    {
        return 'Pelajar Fakulti Ekonomi';
    }
	
    

    
}
