<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Pages;

use Filament\Pages\Dashboard;

/**
 * Custom dashboard (Fixzy SysMaker generated code).
 *
 * Renders the report widgets configured in the Dashboard Builder.
 * Each widget is a generated subclass with its compiled config —
 * see App\Filament\Widgets\Report*.
 */
class FixzyDashboard extends Dashboard
{
    protected static ?string $title = 'Dashboard';

    /**
     * @return array<class-string<\Filament\Widgets\Widget>>
     */
    public function getWidgets(): array
    {
        return [
            \App\Filament\Widgets\Report_w1::class,
            \App\Filament\Widgets\Report_w2::class,
            \App\Filament\Widgets\Report_w3::class,
            \App\Filament\Widgets\Report_w4::class,
            \App\Filament\Widgets\Report_w15::class,
            \App\Filament\Widgets\Report_w7::class,
            \App\Filament\Widgets\Report_w8::class,
            \App\Filament\Widgets\Report_w9::class,
            \App\Filament\Widgets\Report_w10::class,
            \App\Filament\Widgets\Report_w11::class,
            \App\Filament\Widgets\Report_w12::class,
            \App\Filament\Widgets\Report_w13::class,
        ];
    }

    /**
     * @return int | array<string, ?int>
     */
    public function getColumns(): int | array
    {
        return 2;
    }
}
