<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use App\Models\Concerns\HasAudits;

use App\Models\Concerns\HasNumbering;

/**
 * Generated Eloquent model for the tickets table.
 */
class Ticket extends Model 
{
	use HasFactory;
    use HasAudits;
    
    
    use HasNumbering;

    protected static function numberingConfig(): array
    {
        return ['field' => 'ticket_no', 'prefix' => 'TKT', 'date_token' => '', 'width' => 6, 'reset' => 'never'];
    }

    
    /**
     *
     * @var string
     */
    protected $table = 'tickets';
    /**
     *
     * @var string
     */
    protected $primaryKey = 'id';
    /**
     *
     * @var array<int, string>
     */
    protected $fillable = [
        
        'ticket_no',
        'subject',
        'requester_name',
        'requester_email',
        'priority',
        'ticket_status',
        'assigned_to',
        'description'
    
    ];
    
    


    public function ticketReplies()
    {
        return $this->hasMany(TicketReply::class, 'ticket_id', 'id');
    }	




    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (empty($model->created_by)) {
                $model->created_by = auth()->id();
            }
            if (empty($model->updated_by)) {
                $model->updated_by = auth()->id();
            }
        });

        static::updating(function ($model) {
            $model->updated_by = auth()->id();
        });
    }

}
