{{-- Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
Licensed under the Non-Commercial Software License (see LICENSE.md).
This attribution banner must not be removed or altered. --}}
<x-filament-panels::page>
    {{-- Telegram settings: bot token from @BotFather used by workflow "Send
         Telegram" actions, plus a default chat ID for testing. Stored in the
         database, never committed to code. "Send test message" calls the
         testSend Livewire action. --}}
    @if(session('fixzy_settings_saved'))
        <div class="rounded-lg bg-green-50 border border-green-200 text-green-800 px-4 py-3 text-sm dark:bg-green-950 dark:text-green-200 dark:border-green-800">
            {{ session('fixzy_settings_saved') }}
        </div>
    @endif
    @if(session('fixzy_settings_error'))
        <div class="rounded-lg bg-red-50 border border-red-200 text-red-800 px-4 py-3 text-sm dark:bg-red-950 dark:text-red-200 dark:border-red-800">
            {{ session('fixzy_settings_error') }}
        </div>
    @endif

    <form wire:submit="save" class="space-y-6">
        <x-filament::section heading="Bot Credentials">
            <p class="text-sm text-gray-500 mb-4">
                Create a bot with <strong>@BotFather</strong> on Telegram (takes about two minutes),
                then paste the token here. Workflow <strong>Send Telegram</strong> actions use this bot
                at runtime. The token is stored in the database — never committed to code.
            </p>
            <div class="grid gap-4 md:grid-cols-2">
                <label class="block">
                    <span class="text-sm font-medium">Bot token</span>
                    <input type="password" wire:model="settings.telegram_bot_token"
                           placeholder="123456789:AAH4u...your-bot-token"
                           class="mt-1 w-full rounded-lg border-gray-300 shadow-sm dark:bg-gray-800 dark:border-gray-600 px-3 py-2 text-sm" />
                </label>
                <label class="block">
                    <span class="text-sm font-medium">Default chat ID (for testing)</span>
                    <input type="text" wire:model="settings.telegram_default_chat_id"
                           placeholder="-1001234567890 or 123456789"
                           class="mt-1 w-full rounded-lg border-gray-300 shadow-sm dark:bg-gray-800 dark:border-gray-600 px-3 py-2 text-sm" />
                </label>
            </div>
            <p class="text-xs text-gray-400 mt-3">
                Tip: send your bot a message first (or add it to a group) so a chat exists.
                Workflow blocks can override the chat ID per action with
                <code>##variable.telegram_chat_id##</code>.
            </p>
        </x-filament::section>

        <div class="flex justify-end gap-3">
            <x-filament::button type="submit">Save settings</x-filament::button>
            <x-filament::button type="button" color="gray" wire:click="testSend">Send test message</x-filament::button>
        </div>
    </form>
</x-filament-panels::page>

