<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\ProfilPelajar;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ProfilPelajar>
 */
class ProfilPelajarFactory extends Factory
{
    protected $model = ProfilPelajar::class;

    public function definition(): array
    {
        return [
            'pelajar_id' => \App\Models\Pelajar::inRandomOrder()->value('id'),
            'alamat' => fake()->address(),
            'no_telefon' => fake()->phoneNumber(),
            'tarikh_lahir' => fake()->date(),
            'info_kecemasan' => $this->faker->randomElement(['Primary', 'Secondary', 'Diploma', 'Degree', 'Masters', 'PhD']),
        ];
    }
}
