<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Providers;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;

/**
 * Public intake form routes (Fixzy SysMaker generated code).
 *
 * Standalone public routes under /f/{slug} — deliberately OUTSIDE the
 * Filament admin panel. CSRF + session come from the `web` middleware;
 * throttling is enforced inside the controller.
 */
class PublicFormServiceProvider extends ServiceProvider
{
    /**
     * Register the public form, submission and status-lookup routes under /f.
     */
    public function boot(): void
    {
        Route::middleware('web')
            ->prefix('f')
            ->name('public.form.')
            ->group(function (): void {
                Route::get('/{slug}', [\App\Http\Controllers\PublicFormController::class, 'show'])
                    ->name('show');
                Route::post('/{slug}', [\App\Http\Controllers\PublicFormController::class, 'submit'])
                    ->name('submit');
                Route::get('/{slug}/success', [\App\Http\Controllers\PublicFormController::class, 'success'])
                    ->name('success');
                Route::get('/{slug}/status', [\App\Http\Controllers\PublicFormController::class, 'lookupForm'])
                    ->name('lookup');
                Route::post('/{slug}/status', [\App\Http\Controllers\PublicFormController::class, 'lookup'])
                    ->name('lookup.check');
            });
    }
}
