<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\Organisasis;

use App\Filament\Resources\Organisasis\Pages\CreateOrganisasi;
use App\Filament\Resources\Organisasis\Pages\EditOrganisasi;
use App\Filament\Resources\Organisasis\Pages\ListOrganisasis;
use App\Filament\Resources\Organisasis\Schemas\OrganisasiForm;
use App\Filament\Resources\Organisasis\Tables\OrganisasisTable;
use App\Models\Organisasi;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;

use Filament\Actions\Action;
use App\Filament\Actions\PrintAction;

use App\Filament\Imports\OrganisasiImporter;
use Filament\Actions\ImportAction;
use App\Filament\Exports\OrganisasiExporter;
use Filament\Actions\ExportAction;

use App\Filament\Resources\Organisasis\RelationManagers\ProdukRelationManager;
use App\Filament\RelationManagers\AuditsRelationManager;

/**
 * Generated Filament resource for the Organisasi model.
 */
class OrganisasiResource extends Resource
{
    protected static ?string $model = Organisasi::class;
    
        protected static bool $isScopedToTenant = false;


    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    protected static ?int $navigationSort = 1;
    
    

    /**
     * Delegate the form definition to the generated form schema class.
     *
     * @param  Schema  $schema  The resource form schema.
     * @return  Schema  The configured schema.
     */
    public static function form(Schema $schema): Schema
    {
        return OrganisasiForm::configure($schema);
    }

    /**
     * Delegate the table definition and add import/export/print header actions.
     *
     * @param  Table  $table  The resource table instance.
     * @return  Table  The configured table.
     */
    public static function table(Table $table): Table
    {
        return OrganisasisTable::configure($table)
		        ->headerActions([
ImportAction::make()->importer(OrganisasiImporter::class),
ExportAction::make()->exporter(OrganisasiExporter::class)
                /*->enableVisibleTableColumnsByDefault()*/,
			Action::make('print')
                    ->label('Print')
                    ->icon('heroicon-o-printer')
                    ->color('gray')
                    ->url(fn (): string => request()->fullUrlWithQuery(['print' => 1]))
                    ->openUrlInNewTab(),
        ]);
    }

    /**
     * Relation managers shown on the resource, gated by the current user's permissions.
     * @return  array  Relation manager class names.
     */
    public static function getRelations(): array
    {
        $relations = [
                        ProdukRelationManager::class,
        ];
		

    // Only add AuditsRelationManager if the user is allowed to view it
    
        if (auth()->check() && auth()->user()->can('view_any_audit')) {
            $relations[] = AuditsRelationManager::class;
        }
	
	return $relations;
    }

    /**
     * Route bindings for the resource's list, create and edit pages.
     * @return  array  Page name to route mapping.
     */
    public static function getPages(): array
    {
        return [
            'index' => ListOrganisasis::route('/'),
            'create' => CreateOrganisasi::route('/create'),
            'edit' => EditOrganisasi::route('/{record}/edit'),
        ];
    }
	
    // 1. Set the URL
    protected static ?string $slug = 'organisasi';

    // 2. Set the label for a single record
    /**
     * Singular label for the model.
     * @return  string  Singular model label.
     */
    public static function getModelLabel(): string
    {
        return 'Organisasi';
    }

    // 3. Set the label for multiple records (main resource page title)
    /**
     * Plural label used in the navigation menu.
     * @return  string  Plural model label.
     */
    public static function getPluralModelLabel(): string
    {
        return 'Organisasi';
    }
	
    

    

    
}
