<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\FakultiBoards\Tables;



use App\Models\Fakulti;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\ForceDeleteAction;
use Filament\Actions\RestoreAction;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Columns\TextInputColumn;
use Filament\Tables\Columns\ToggleColumn;
use Filament\Support\Enums\TextSize;
use Illuminate\Contracts\View\View;


/**
 * Generated table configuration fragment for this table.
 */
class FakultiBoardsTable
{
    /**
     * Apply pagination, columns and display options to the table.
     *
     * @param  Table  $table  The table instance to configure.
     * @return  Table  The configured table.
     */
    public static function configure(Table $table): Table
    {
        return $table
            
            
            ->defaultPaginationPageOption(25)->paginationPageOptions([10, 25, 50])
            
            
            
            ->extraAttributes(['class' => 'fixzy-sticky-header fixzy-grid-compact fixzy-grid-striped'])
            ->description('')
            ->columns([
                TextInputColumn::make('nama_fakulti')
                    ->label('Nama Fakulti')
                    ->rules(['max:255'])
                    ->updateStateUsing(function ($record, $state) {
                    // Match Filament resource authorization semantics: deny only when a
                    // policy exists and denies. Raw Gate::can() denies when NO
                    // policy exists, which 403'd every inline edit while the
                    // resource's own canEdit() allowed it (grid audit 2026-09-30).
                    if (\Illuminate\Support\Facades\Gate::getPolicyFor($record) && ! auth()->user()?->can('update', $record)) {
                        abort(403);
                    }
                    if (is_null($state)) {
                        $record->nama_fakulti = null;
                    } else {
                        $record->nama_fakulti = $state;
                    }
                    $record->save();
                    return $record;
                })
                    ->searchable(),
                ToggleColumn::make('is_aktif')
                    ->label('Aktif')
                    ->rules(['boolean'])
                    ->updateStateUsing(function ($record, $state) {
                    // Match Filament resource authorization semantics: deny only when a
                    // policy exists and denies. Raw Gate::can() denies when NO
                    // policy exists, which 403'd every inline edit while the
                    // resource's own canEdit() allowed it (grid audit 2026-09-30).
                    if (\Illuminate\Support\Facades\Gate::getPolicyFor($record) && ! auth()->user()?->can('update', $record)) {
                        abort(403);
                    }
                    if (is_null($state)) {
                        $record->is_aktif = null;
                    } else {
                        $record->is_aktif = $state;
                    }
                    $record->save();
                    return $record;
                })
                    ->searchable(),
                TextColumn::make('status_kerja')
                    ->label('Status')
                    ->sortable()
                    ->limit(50, end: ' (more)')
                    ->color('success')
                    ->size(TextSize::Medium)
                    ->searchable()
                    ->toggleable()
                    ->alignCenter()
                    ->badge()->color(fn (string $state): string => match ($state) {
        'Draft' => 'gray',
        'Review' => 'info',
        'Approved' => 'primary',
        })
            ])
            ->when((bool) request()->query('print'), fn (Table $table) => $table->paginated(false),)
            ->filters([
                TrashedFilter::make(),
            ])
            ->recordActions([

                   
                    
                
                
                ForceDeleteAction::make(),
                RestoreAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                DeleteBulkAction::make(),
            ]),
            ]);
    }
}