<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace App\Filament\Resources\DokumenBerjenis\Schemas;



use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Model;
use Filament\Schemas\Schema;
use Filament\Pages\Page;
use Filament\Schemas\Components\Section;
use Filament\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\FileUpload;

/**
 * Generated form schema fragment for this table's fields.
 */
class DokumenBerjeniForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make("Detail View")
                ->columns(fn (Page $livewire) => $livewire->gridColumns)
    ->headerActions([
        Action::make('1 Kolum')
            ->icon('heroicon-o-queue-list')
            ->iconButton()
            ->color('gray')
            ->tooltip('Display 1 column')
            ->action(fn (Page $livewire) => $livewire->gridColumns = 1),

        Action::make('2 Kolum')
            ->icon('heroicon-o-view-columns')
            ->iconButton()
            ->color('gray')
            ->tooltip('Display 2 column')
            ->action(fn (Page $livewire) => $livewire->gridColumns = 2),

        Action::make('3 Kolum')
            ->icon('heroicon-o-table-cells')
            ->iconButton()
            ->color('gray')
            ->tooltip('Display 3 column')
            ->action(fn (Page $livewire) => $livewire->gridColumns = 3),
    ])
                ->schema([
				TextInput::make('id')
    ->integer()
    ->readOnly()
    ->maxLength(255)
    ->label('Id')
    ->trim(),
                TextInput::make('tajuk')
    ->maxLength(120)
    ->required()->markAsRequired()
    ->label('Tajuk')
    ->trim(),
                FileUpload::make('lampiran')
    ->label('Lampiran')
    ->multiple()
    ->maxFiles(5)
    ->maxSize(10240)
    ->directory('attachments/lampiran')
    ->disk('local')
    ->visibility('private')
    ->columnSpanFull()
    ->acceptedFileTypes(['application/pdf', 'image/png', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']),
                Select::make('pemilik')
    ->required()->markAsRequired()
    ->label('Pemilik')
    ->relationship('user', 'name')
    ->getOptionLabelFromRecordUsing(fn (Model $record) => "{$record->name} - {$record->email}")
    ,
                ])
                ->columnSpanFull(),
        ]);
    }
}