<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace App\Filament\Resources\FakultiWizards\Schemas;



use Illuminate\Contracts\View\View;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Wizard;
use Filament\Schemas\Components\Wizard\Step;
use Filament\Forms\Components\TextInput;

/**
 * Generated form schema fragment for this table's fields.
 */
class FakultiWizardForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
			Wizard::make()
    ->startOnStep(1)
    ->steps([
Step::make('Main Info')
    ->schema([
TextInput::make('nama_fakulti')
    ->maxLength(150)
    ->required()->markAsRequired()
    ->label('Nama Fakulti')
    ->trim(),
    ]),
Step::make('Extra')
    ->schema([
TextInput::make('kod_fakulti')
    ->maxLength(20)
    ->unique(ignoreRecord: true)
    ->label('Kod Fakulti')
    ->trim(),
    ]),
Step::make('Other')
    ->schema([
TextInput::make('id')
    ->integer()
    ->readOnly()
    ->maxLength(255)
    ->label('Id')
    ->trim(),
    ])])
        ]);
    }
}