<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Tempahan;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Tempahan>
 */
class TempahanFactory extends Factory
{
    protected $model = Tempahan::class;

    public function definition(): array
    {
        return [
            'nama' => fake()->name(),
            'country' => $this->faker->randomElement(['MY', 'SG', 'TH']),
            'state' => $this->faker->randomElement(['Johor', 'Selangor', 'Perlis']),
            'notes' => fake()->text(),
            'agree' => fake()->boolean(),
        ];
    }
}
