<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Resources\Asets;

use App\Filament\Resources\Asets\Pages\CreateAset;
use App\Filament\Resources\Asets\Pages\EditAset;
use App\Filament\Resources\Asets\Pages\ListAsets;
use App\Filament\Resources\Asets\Schemas\AsetForm;
use App\Filament\Resources\Asets\Tables\AsetsTable;
use App\Models\Aset;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Filament\Actions\Action;
use App\Filament\Actions\PrintAction;

use App\Filament\Imports\AsetImporter;
use Filament\Actions\ImportAction;
use App\Filament\Exports\AsetExporter;
use Filament\Actions\ExportAction;


use App\Filament\RelationManagers\AuditsRelationManager;

/**
 * Generated Filament resource for the Aset model.
 */
class AsetResource extends Resource
{
    protected static ?string $model = Aset::class;
    
    

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    
    
    
    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->where('created_by', auth()->id());
    }

    /**
     * Delegate the form definition to the generated form schema class.
     *
     * @param  Schema  $schema  The resource form schema.
     * @return  Schema  The configured schema.
     */
    public static function form(Schema $schema): Schema
    {
        return AsetForm::configure($schema);
    }

    /**
     * Delegate the table definition and add import/export/print header actions.
     *
     * @param  Table  $table  The resource table instance.
     * @return  Table  The configured table.
     */
    public static function table(Table $table): Table
    {
        return AsetsTable::configure($table)
		        ->headerActions([
ImportAction::make()->importer(AsetImporter::class),
ExportAction::make()->exporter(AsetExporter::class)
                /*->enableVisibleTableColumnsByDefault()*/,
			Action::make('print')
                    ->label('Print')
                    ->icon('heroicon-o-printer')
                    ->color('gray')
                    ->url(fn (): string => request()->fullUrlWithQuery(['print' => 1]))
                    ->openUrlInNewTab(),
        ]);
    }

    /**
     * Relation managers shown on the resource, gated by the current user's permissions.
     * @return  array  Relation manager class names.
     */
    public static function getRelations(): array
    {
        $relations = [
            
        ];
		

    // Only add AuditsRelationManager if the user is allowed to view it
    
        if (auth()->check() && auth()->user()->can('view_any_audit')) {
            $relations[] = AuditsRelationManager::class;
        }
	
	return $relations;
    }

    /**
     * Route bindings for the resource's list, create and edit pages.
     * @return  array  Page name to route mapping.
     */
    public static function getPages(): array
    {
        return [
            'index' => ListAsets::route('/'),
            'create' => CreateAset::route('/create'),
            'edit' => EditAset::route('/{record}/edit'),
        ];
    }
	
    // 1. Set the URL
    protected static ?string $slug = 'aset';

    // 2. Set the label for a single record
    /**
     * Singular label for the model.
     * @return  string  Singular model label.
     */
    public static function getModelLabel(): string
    {
        return 'Aset';
    }

    // 3. Set the label for multiple records (main resource page title)
    /**
     * Plural label used in the navigation menu.
     * @return  string  Plural model label.
     */
    public static function getPluralModelLabel(): string
    {
        return 'Pelajar Fakulti Ekonomi';
    }
	
    

    
}
