{{-- Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
Licensed under the Non-Commercial Software License (see LICENSE.md).
This attribution banner must not be removed or altered. --}}
<x-filament-panels::page>
    {{-- Activity log page: filterable audit views. "Sign-in activity" lists auth
         events (login / logout / failed); "Data changes" lists per-user model
         audits (tab only rendered when audit is enabled). All filters use
         wire:model.live so changing one re-renders the table server-side. --}}
    {{-- Filter bar: user, event type (auth tab only), and date range. --}}
    <x-filament::section>
        <div class="flex flex-wrap items-end gap-3">
            <div class="flex flex-col gap-1">
                <label class="text-xs font-medium text-gray-600 dark:text-gray-300" for="flt-user">User</label>
                <select id="flt-user" wire:model.live="userId"
                      class="rounded-lg border-gray-300 shadow-sm dark:bg-gray-800 dark:border-gray-600 px-3 py-1.5 text-sm">
                    <option value="">All users</option>
                    @foreach ($userOptions as $id => $name)
                        <option value="{{ $id }}" @selected((string) $userId === (string) $id)>{{ $name }}</option>
                    @endforeach
                </select>
            </div>

            @if ($tab === 'auth')
            <div class="flex flex-col gap-1">
                <label class="text-xs font-medium text-gray-600 dark:text-gray-300" for="flt-event">Event</label>
                <select id="flt-event" wire:model.live="event"
                      class="rounded-lg border-gray-300 shadow-sm dark:bg-gray-800 dark:border-gray-600 px-3 py-1.5 text-sm">
                    <option value="">All events</option>
                    <option value="logged_in" @selected($event === 'logged_in')>Signed in</option>
                    <option value="logged_out" @selected($event === 'logged_out')>Signed out</option>
                    <option value="login_failed" @selected($event === 'login_failed')>Failed sign-in</option>
                </select>
            </div>
            @endif

            <div class="flex flex-col gap-1">
                <label class="text-xs font-medium text-gray-600 dark:text-gray-300" for="flt-from">From</label>
                <input type="date" id="flt-from" wire:model.live="dateFrom" value="{{ $dateFrom }}"
                      class="rounded-lg border-gray-300 shadow-sm dark:bg-gray-800 dark:border-gray-600 px-3 py-1.5 text-sm">
            </div>
            <div class="flex flex-col gap-1">
                <label class="text-xs font-medium text-gray-600 dark:text-gray-300" for="flt-to">To</label>
                <input type="date" id="flt-to" wire:model.live="dateTo" value="{{ $dateTo }}"
                      class="rounded-lg border-gray-300 shadow-sm dark:bg-gray-800 dark:border-gray-600 px-3 py-1.5 text-sm">
            </div>

            <x-filament::button tag="a" href="{{ static::getUrl() }}" color="gray" size="sm">Reset</x-filament::button>
        </div>
    </x-filament::section>

    
    <div class="flex gap-2">
        <button wire:click="setTab('auth')"
           class="px-3 py-1.5 rounded-lg text-sm font-medium {{ $tab === 'auth' ? 'bg-primary-600 text-white' : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-200' }}">
            Sign-in activity
        </button>
        <button wire:click="setTab('data')"
           class="px-3 py-1.5 rounded-lg text-sm font-medium {{ $tab === 'data' ? 'bg-primary-600 text-white' : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-200' }}">
            Data changes
        </button>
    </div>
    

    <x-filament::section>
        @if ($tab === 'auth')
            <div class="overflow-x-auto">
                <table class="w-full text-sm">
                    <thead>
                        <tr class="text-left text-xs font-semibold text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">
                            <th class="py-2 pr-4">When</th>
                            <th class="py-2 pr-4">User</th>
                            <th class="py-2 pr-4">Event</th>
                            <th class="py-2 pr-4">Details</th>
                            <th class="py-2">IP address</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($activityRecords as $log)
                            <tr class="border-b border-gray-100 dark:border-gray-800">
                                <td class="py-2 pr-4 whitespace-nowrap">{{ $log->created_at?->format('d M Y H:i') }}</td>
                                <td class="py-2 pr-4">{{ $log->user?->name ?? '—' }}</td>
                                <td class="py-2 pr-4">
                                    @php
                                        $badge = match ($log->event) {
                                            'logged_in' => 'success',
                                            'logged_out' => 'gray',
                                            'login_failed' => 'danger',
                                            default => 'gray',
                                        };
                                    @endphp
                                    <x-filament::badge :color="$badge">{{ str_replace('_', ' ', $log->event) }}</x-filament::badge>
                                </td>
                                <td class="py-2 pr-4 text-gray-600 dark:text-gray-300">{{ $log->description }}</td>
                                <td class="py-2 text-gray-500 dark:text-gray-400">{{ $log->ip_address }}</td>
                            </tr>
                        @empty
                            <tr><td colspan="5" class="py-8 text-center text-gray-400">No sign-in activity matches the filters.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        @else
            @if (! $userId)
                <p class="py-8 text-center text-gray-400">Select a user above to see the data they changed (Data Audit Trail).</p>
            @else
                <div class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead>
                            <tr class="text-left text-xs font-semibold text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">
                                <th class="py-2 pr-4">When</th>
                                <th class="py-2 pr-4">Record type</th>
                                <th class="py-2 pr-4">Record ID</th>
                                <th class="py-2 pr-4">Action</th>
                                <th class="py-2">Changes</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($dataChangeRecords as $audit)
                                <tr class="border-b border-gray-100 dark:border-gray-800 align-top">
                                    <td class="py-2 pr-4 whitespace-nowrap">{{ $audit->created_at?->format('d M Y H:i') }}</td>
                                    <td class="py-2 pr-4">{{ $audit->type_label }}</td>
                                    <td class="py-2 pr-4">{{ $audit->auditable_id }}</td>
                                    <td class="py-2 pr-4">
                                        @php
                                            $badge = match ($audit->event) {
                                                'created' => 'success',
                                                'updated' => 'warning',
                                                'deleted' => 'danger',
                                                default => 'gray',
                                            };
                                        @endphp
                                        <x-filament::badge :color="$badge">{{ $audit->event }}</x-filament::badge>
                                    </td>
                                    <td class="py-2 text-gray-600 dark:text-gray-300">
                                        @if (! empty($audit->new_values))
                                            <details>
                                                <summary class="cursor-pointer text-primary-600 dark:text-primary-400">View values</summary>
                                                <pre class="mt-2 text-xs bg-gray-50 dark:bg-gray-800 rounded p-2 overflow-x-auto">{{ json_encode(['old' => $audit->old_values, 'new' => $audit->new_values], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>
                                            </details>
                                        @else
                                            <span class="text-gray-400">—</span>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr><td colspan="5" class="py-8 text-center text-gray-400">No data changes by this user in this period.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            @endif
        @endif
    </x-filament::section>

    <p class="text-xs text-gray-400">
        Showing the latest 200 entries. Narrow the date range for older records.
    </p>
</x-filament-panels::page>
