<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Imports;

use App\Models\MatrixRecord;
use App\Models\Character;
use Filament\Actions\Imports\ImportColumn;
use Filament\Actions\Imports\Importer;
use Filament\Actions\Imports\Models\Import;
use Illuminate\Support\Number;
use Filament\Forms\Components\Checkbox;

/**
 * Generated importer for Matrix Records rows from CSV/XLSX.
 */
class MatrixRecordImporter extends Importer
{
    protected static ?string $model = MatrixRecord::class;

    /**
     * Mappable import columns with type casts and rules.
     * @return  array  ImportColumn definitions.
     */
    public static function getColumns(): array
    {
        return [
            ImportColumn::make('id')
                ->label('ID')
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('ID'),

            ImportColumn::make('txt_plain')
                ->label('Plain Text')
                ->requiredMapping()
                ->ignoreBlankState()
                ->rules(['required', 'max:255'])
                ->examples(['Sample Plain Text 1', 'Sample Plain Text 2'])
                ->exampleHeader('Plain Text'),

            ImportColumn::make('txt_email')
                ->label('Email')
                ->ignoreBlankState()
                ->rules(['max:255', 'email'])
                ->examples(['user1@example.com', 'user2@example.com'])
                ->exampleHeader('Email'),

            ImportColumn::make('txt_url')
                ->label('URL')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample URL 1', 'Sample URL 2'])
                ->exampleHeader('URL'),

            ImportColumn::make('txt_tel')
                ->label('Telephone')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Telephone 1', 'Sample Telephone 2'])
                ->exampleHeader('Telephone'),

            ImportColumn::make('txt_password')
                ->label('Password')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Password 1', 'Sample Password 2'])
                ->exampleHeader('Password'),

            ImportColumn::make('num_int')
                ->label('Integer')
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('Integer'),

            ImportColumn::make('num_decimal')
                ->label('Decimal')
                ->numeric()
                ->ignoreBlankState()
                ->rules(['max:10'])
                ->examples(['Sample Decimal 1', 'Sample Decimal 2'])
                ->exampleHeader('Decimal'),

            ImportColumn::make('dt_date')
                ->label('Date')
                ->ignoreBlankState()
                ->rules(['max:255', 'date'])
                ->examples(['2024-01-01', '2024-12-31'])
                ->exampleHeader('Date'),

            ImportColumn::make('dt_datetime')
                ->label('Datetime')
                ->ignoreBlankState()
                ->rules(['max:255', 'datetime'])
                ->examples(['2024-01-01 22:56:00', '2024-12-31 22:56:00'])
                ->exampleHeader('Datetime'),

            ImportColumn::make('txt_area')
                ->label('Text Area')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Text Area 1', 'Sample Text Area 2'])
                ->exampleHeader('Text Area'),

            ImportColumn::make('txt_rich')
                ->label('Rich Editor')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Rich Editor 1', 'Sample Rich Editor 2'])
                ->exampleHeader('Rich Editor'),

            ImportColumn::make('bool_check')
                ->label('Checkbox')
                ->boolean()
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['1', '0'])
                ->exampleHeader('Checkbox'),

            ImportColumn::make('opt_dropdown')
                ->label('Options Dropdown')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Options Dropdown 1', 'Sample Options Dropdown 2'])
                ->exampleHeader('Options Dropdown'),

            ImportColumn::make('opt_radios')
                ->label('Options Radios')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Options Radios 1', 'Sample Options Radios 2'])
                ->exampleHeader('Options Radios'),

            ImportColumn::make('opt_checkboxes')
                ->label('Options Checkboxes')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Options Checkboxes 1', 'Sample Options Checkboxes 2'])
                ->exampleHeader('Options Checkboxes'),

            ImportColumn::make('opt_multi')
                ->label('Options Multi')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Options Multi 1', 'Sample Options Multi 2'])
                ->exampleHeader('Options Multi'),

            ImportColumn::make('character')
                ->label('nama_watak')
                ->relationship(resolveUsing: ['nama_watak'])
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('nama_watak'),

            ImportColumn::make('character')
                ->label('nama_watak')
                ->relationship(resolveUsing: ['nama_watak'])
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('nama_watak'),

            ImportColumn::make('rep_simple')
                ->label('Repeater Simple')
                ->multiple(',')
                ->ignoreBlankState()
                ->rules(['max:255', 'array'])
                ->examples(['Sample Repeater Simple 1', 'Sample Repeater Simple 2'])
                ->exampleHeader('Repeater Simple'),

            ImportColumn::make('rep_complex')
                ->label('Repeater Complex')
                ->multiple(',')
                ->ignoreBlankState()
                ->rules(['max:255', 'array'])
                ->examples(['Sample Repeater Complex 1', 'Sample Repeater Complex 2'])
                ->exampleHeader('Repeater Complex'),

            ImportColumn::make('img_profile')
                ->label('Profile Picture')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Profile Picture 1', 'Sample Profile Picture 2'])
                ->exampleHeader('Profile Picture'),

            ImportColumn::make('img_avatar')
                ->label('Avatar Circular')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Avatar Circular 1', 'Sample Avatar Circular 2'])
                ->exampleHeader('Avatar Circular'),

            ImportColumn::make('file_doc')
                ->label('Document')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Document 1', 'Sample Document 2'])
                ->exampleHeader('Document'),

            ImportColumn::make('file_multi')
                ->label('Attachments')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Attachments 1', 'Sample Attachments 2'])
                ->exampleHeader('Attachments'),

            ImportColumn::make('map_loc')
                ->label('Location Map')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Location Map 1', 'Sample Location Map 2'])
                ->exampleHeader('Location Map'),

            ImportColumn::make('vid_clip')
                ->label('Video Clip')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Video Clip 1', 'Sample Video Clip 2'])
                ->exampleHeader('Video Clip'),

            ImportColumn::make('color_hex')
                ->label('Event Color')
                ->ignoreBlankState()
                ->rules(['max:255'])
                ->examples(['Sample Event Color 1', 'Sample Event Color 2'])
                ->exampleHeader('Event Color'),
        ];
    }

    /**
     * Resolve which record this imported row maps to (generated custom logic).
     * @return  ?MatrixRecord  Resolved record instance.
     */
    public function resolveRecord(): ?MatrixRecord
    {
    return new MatrixRecord();
    }

    /**
     * Notification body shown when the import finishes.
     *
     * @param  Import  $import  The completed import job.
     * @return  string  Human-readable completion summary.
     */
    public static function getCompletedNotificationBody(Import $import): string
    {
        $body = 'Your Matrix Records import has completed and ' . Number::format($import->successful_rows) . ' ' . str('row')->plural($import->successful_rows) . ' imported.';

        if ($failedRowsCount = $import->getFailedRowsCount()) {
            $body .= ' ' . Number::format($failedRowsCount) . ' ' . str('row')->plural($failedRowsCount) . ' failed to import.';
        }

        return $body;
    }
    
    /**
     * Extra options form shown before importing (dry run / update existing).
     * @return  array  Form component definitions.
     */
    public static function getOptionsFormComponents(): array
    {
        return [
            Checkbox::make('updateExisting')
                ->label('Update existing records'),
        ];
    }

}
