<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('matriks', function (Blueprint $table) {
            $table->id();
            $table->string('txt_plain', 255);
            $table->string('txt_email', 255);
            $table->string('txt_url', 255);
            $table->string('txt_tel', 255);
            $table->string('txt_password', 255);
            $table->integer('num_int');
            $table->decimal('num_decimal', 10, 2);
            $table->date('dt_date');
            $table->dateTime('dt_datetime');
            $table->text('txt_area');
            $table->text('txt_rich');
            $table->boolean('bool_check');
            $table->string('opt_dropdown', 255);
            $table->string('opt_radios', 255);
            $table->string('opt_checkboxes', 255);
            $table->string('opt_multi', 255);
            $table->foreignId('lk_dropdown');
            $table->foreignId('lk_radios');
            $table->json('rep_simple');
            $table->json('rep_complex');
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('matriks');
    }
};