<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('matriks', function (Blueprint $table) {
            $table->id();
            $table->string('txt_plain', 255);
            $table->string('txt_email', 255)->nullable();
            $table->string('txt_url', 255)->nullable();
            $table->string('txt_tel', 255)->nullable();
            $table->string('txt_password', 255)->nullable();
            $table->integer('num_int')->nullable();
            $table->decimal('num_decimal', 10, 2)->nullable();
            $table->date('dt_date')->nullable();
            $table->dateTime('dt_datetime')->nullable();
            $table->text('txt_area')->nullable();
            $table->text('txt_rich')->nullable();
            $table->boolean('bool_check')->nullable();
            $table->string('opt_dropdown', 255)->nullable();
            $table->string('opt_radios', 255)->nullable();
            $table->string('opt_checkboxes', 255)->nullable();
            $table->string('opt_multi', 255)->nullable();
            $table->foreignId('lk_dropdown')->nullable();
            $table->foreignId('lk_radios')->nullable();
            $table->json('rep_simple')->nullable();
            $table->json('rep_complex')->nullable();
            $table->string('img_profile', 255)->nullable();
            $table->string('img_avatar', 255)->nullable();
            $table->string('file_doc', 255)->nullable();
            $table->text('file_multi')->nullable();
            $table->string('map_loc', 255)->nullable();
            $table->string('vid_clip', 255)->nullable();
            $table->string('color_hex', 255)->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('matriks');
    }
};