<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('matriks', function (Blueprint $table) {
            $table->foreign(['lk_dropdown'])->references(['id'])->on('watak')->onUpdate('cascade')->onDelete('cascade');
            $table->foreign(['lk_radios'])->references(['id'])->on('watak')->onUpdate('cascade')->onDelete('cascade');
        });
    }

    public function down(): void
    {
        Schema::table('matriks', function (Blueprint $table) {
            $table->dropForeign(['lk_dropdown']);
            $table->dropForeign(['lk_radios']);
        });
    }
};