<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace App\Filament\Resources\Complaints\Schemas;



use Illuminate\Contracts\View\View;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Section;
use Filament\Forms\Components\ViewField;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Checkbox;
use Filament\Forms\Components\Radio;
use Filament\Forms\Components\Repeater;

/**
 * Generated form schema fragment for this table's fields.
 */
class ComplaintForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make("")
                ->columns([
        'default' => 1,
        'md' => 2,
        
    ])
                ->schema([
				TextInput::make('id')
    ->integer()
    ->maxLength(255)
    ->label('ID')
    ->trim(),
                TextInput::make('txt_plain')
    ->maxLength(255)
    ->required()->markAsRequired()
    ->label('Full Name')
    ->trim(),
                TextInput::make('txt_email')
    ->email()
    ->maxLength(255)
    ->required()->markAsRequired()
    ->label('Email')
    ->trim(),
                Textarea::make('txt_area')
    ->maxLength(255)
    ->label('Description')
    ->trim(),
                RichEditor::make('txt_rich')
    ->maxLength(255)
    ->label('Rich Details')
    ,
                Checkbox::make('bool_urgent')
    ->label('Urgent')
    ,
                Select::make('opt_category')
    ->label('Category')
    ->options(['rosak' => 'Rosak', 'hilang' => 'Hilang', 'lain' => 'Lain'])
    ,
                Select::make('opt_channels')
    ->label('Contact Channels')
    ->multiple()
->options(['email' => 'Email', 'telefon' => 'Telefon', 'sms' => 'Sms'])
    ,
                Radio::make('opt_priority')
    ->label('Priority')
    ->options(['rendah' => 'Rendah', 'sederhana' => 'Sederhana', 'tinggi' => 'Tinggi'])
    ,
                Select::make('lk_watak')
    ->label('Related Character')
    ->relationship('character', 'nama_watak')
    ,
                Radio::make('lk_watak_radio')
    ->label('Favourite Character')
    ->options(fn () => \App\Models\Character::orderBy('nama_watak')->pluck('nama_watak', 'id'))
    ,
                Repeater::make('rep_notes')
    ->label('Extra Notes')
    ->simple(
        TextInput::make('rep_notes')->unique(ignoreRecord: true),
    )
    ->reorderable(false),
                TextInput::make('num_amount')
    ->numeric()->rule('decimal:0,2')
    ->label('Claim Amount')
    ->trim(),
                DatePicker::make('dt_event')
    ->label('Event Date')
    ,
                DateTimePicker::make('dt_report')
    ->label('Report Datetime')
    ,
                Select::make('aduan_status')
    ->label('Status')
    ->options(['pending' => 'Pending', 'proses' => 'Proses', 'selesai' => 'Selesai'])
    ,
                FileUpload::make('img_proof')
    ->label('Photo Evidence')
    ->image()
    ->imageEditor()
    ->directory('img-proof')
    ->disk('public')
    ->downloadable(),
                FileUpload::make('doc_form')
    ->label('Supporting Doc')
    ->directory('doc-form')
    ->disk('public')
    ->acceptedFileTypes(['application/pdf', 'text/plain'])
    ->downloadable()
    ->openable(),
                FileUpload::make('files_extra')
    ->label('Extra Attachments')
    ->multiple()
    ->maxFiles(2)
    ->maxSize(1024)
    ->directory('attachments/files-extra')
    ->disk('local')
    ->visibility('private')
    ->columnSpanFull()
    ->acceptedFileTypes(['application/pdf', 'text/plain']),
                TextInput::make('map_place')
    ->label('Location (embed)')
    ->columnSpanFull(),
ViewField::make('map_place')
    ->view('filament.forms.components.map-viewer')
    ->columnSpanFull(),
                TextInput::make('vid_evidence')
    ->label('Video (embed)')
    ->columnSpanFull(),
ViewField::make('vid_evidence')
    ->view('filament.forms.components.video-viewer')
    ->columnSpanFull(),
                TextInput::make('internal_note')
    ->maxLength(255)
    ->label('Internal Note')
    ->trim(),
                ])
                ->columnSpanFull(),
        ]);
    }
}