// Nunjucks render engine (Phase 2).
//
// Replaces the <<PLACEHOLDER>> string-replacement machinery with real
// templates: logic lives IN the template, JS only supplies data.
//
// Conventions:
//  - Templates live under src/templates/php/filament/ with .njk extension
//    (e.g. 'app/Filament/Pages/DeploymentGuide.php.njk').
//  - autoescape OFF: output is PHP/Blade/markdown, not HTML from user input.
//    Generators are responsible for escaping identifiers at context-build
//    time (they already sanitize table/field names upstream).
//  - trimBlocks + lstripBlocks: {% %} control lines don't emit blank lines,
//    keeping generated code clean without manual newline gymnastics.

'use strict';

const path = require('path');
const nunjucks = require('nunjucks');

const utils = require('../utils');

const TEMPLATE_ROOT = path.join(__dirname, '..', 'templates', 'php', 'filament');

const env = new nunjucks.Environment(
    new nunjucks.FileSystemLoader(TEMPLATE_ROOT, { watch: false, noCache: false }),
    {
        autoescape: false,
        // trimBlocks/lstripBlocks intentionally OFF: they merge content lines
        // around inline {% endraw %}...{% raw %} boundaries (byte-level
        // corruption in mixed Blade templates) and would change whitespace in
        // migrated templates. Templates control their own whitespace instead.
        trimBlocks: false,
        lstripBlocks: false,
        throwOnUndefined: true,
    }
);

// Case-conversion helpers (same functions the generators use today).
env.addFilter('pascal', utils.toPascalCase);
env.addFilter('camel', utils.toCamelCase);
env.addFilter('plural_pascal', utils.toPluralPascalCase);
env.addFilter('plural_camel', utils.toPluralCamelCase);
env.addFilter('singular_pascal', utils.toSingularPascalCase);
env.addFilter('singular_camel', utils.toSingularCamelCase);
env.addFilter('flat', utils.toFlatCase);
env.addFilter('title', utils.toTitleCase);

// Data helpers usable from templates.
env.addFilter('migration_def', utils.getFieldDefinitionForMigration);
env.addFilter('faker_formatter', utils.getFakerFormatter);
env.addFilter('php_date_format', utils.convertDateFormatToPhp);
env.addFilter('eloquent_rules', utils.buildEloquentQueryFromRules);

// Generic filters.
env.addFilter('json', (v, indent) => JSON.stringify(v, null, indent || 0));
env.addFilter('snake', (s) => String(s || '').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase());

// ---------------------------------------------------------------------------
// License attribution banner (mandatory — see LICENSE.md Section 2).
//
// Every file emitted through renderTemplate() gets this banner prepended so the
// credit survives redistribution of generated projects. Removing, obscuring, or
// disabling it terminates the license (LICENSE.md Section 5). Do NOT bypass
// renderTemplate() for generated output.
// ---------------------------------------------------------------------------
const BANNER_TEXT = 'Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.\n' +
    'Licensed under the Non-Commercial Software License (see LICENSE.md).\n' +
    'This attribution banner must not be removed or altered.';

/**
 * Build the attribution banner comment for a rendered file.
 * @param {string} templateName template path (used to pick the comment syntax)
 * @returns {string} banner comment block including trailing newline ('' if N/A)
 */
function bannerFor(templateName) {
    const name = String(templateName);
    if (name.endsWith('.blade.php.njk')) {
        return `{{-- ${BANNER_TEXT} --}}\n`;
    }
    // schemas/*.php.njk are fragments embedded inside generated classes —
    // they inherit the parent file's banner; adding <?php there would be fatal.
    if (name.endsWith('.php.njk') && !name.startsWith('schemas/')) {
        return `<?php\n\n/**\n * ${BANNER_TEXT.replace(/\n/g, '\n * ')}\n */\n`;
    }
    return '';
}

/**
 * Render a template (path relative to src/templates/php/filament) with context.
 * Prepends the mandatory license attribution banner (see bannerFor).
 * @param {string} templateName e.g. 'app/Filament/Pages/DeploymentGuide.php.njk'
 * @param {object} context
 * @returns {string} rendered output
 */
function renderTemplate(templateName, context) {
    const rendered = env.render(templateName, context || {});
    const name = String(templateName);
    const banner = bannerFor(name);
    if (!banner) return rendered;
    if (name.endsWith('.php.njk') && !name.endsWith('.blade.php.njk')) {
        // Strip the template's own opening <?php tag; the banner supplies it.
        return banner + rendered.replace(/^\s*<\?php\r?\n/, '');
    }
    return banner + rendered;
}

/** Render a template string directly (for tests / dynamic templates). */
function renderString(src, context) {
    return env.renderString(src, context || {});
}

/**
 * Prepend the license attribution docblock to a string-built PHP source.
 * For generators that build PHP with template literals instead of .njk files.
 * Inserts the banner right after the opening `<?php` tag.
 * @param {string} phpSource full PHP source starting with `<?php`
 * @returns {string} source with the mandatory banner inserted
 */
function withBannerPhp(phpSource) {
    const doc = `/**\n * ${BANNER_TEXT.replace(/\n/g, '\n * ')}\n */\n`;
    return String(phpSource).replace(/^<\?php\r?\n/, `<?php\n\n${doc}`);
}

module.exports = { env, renderTemplate, renderString, withBannerPhp, TEMPLATE_ROOT };
