<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\SimpleForm;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\SimpleForm>
 */
class SimpleFormFactory extends Factory
{
    protected $model = SimpleForm::class;

    public function definition(): array
    {
        return [
            'nota' => fake()->word(),
        ];
    }
}
