<?php

namespace App\Filament\Auth;

use Filament\Auth\Http\Responses\Contracts\LoginResponse;
use Filament\Auth\Pages\Login;
use Filament\Forms\Components\TextInput;
use Filament\Notifications\Notification;
use Filament\Schemas\Schema;
use Illuminate\Validation\ValidationException;

/**
 * Combined login page generated by Fixzy SysMaker.
 *
 * Includes only the features enabled in the project settings:
 *   - captcha: built-in arithmetic human check (no third-party service)
 *   - LDAP:    directory authentication via App\Services\LdapAuthenticator
 *   - Google SSO button (handled by routes; shown via panel render hook)
 */
class FixzyLogin extends Login
{
    public function form(Schema $schema): Schema
    {
        $components = [
            $this->getEmailFormComponent(),
            $this->getPasswordFormComponent(),
            $this->getRememberFormComponent(),
        ];

        

        

        return $schema->components($components);
    }

    
    /**
     * LDAP usernames are not always email addresses, so relax the email
     * format rule and label the field accordingly.
     */
    protected function getEmailFormComponent(): \Filament\Schemas\Components\Component
    {
        return TextInput::make('email')
            ->label('Username or email')
            ->required()
            ->autocomplete()
            ->autofocus()
            ->extraInputAttributes(['tabindex' => 1]);
    }

    public function authenticate(): ?LoginResponse
    {
        // getState() runs ALL form validation first — including the
        // captcha rule when enabled — so the LDAP fallback below can
        // never be reached with a failed human check.
        $data = $this->form->getState();

        try {
            return parent::authenticate();
        } catch (ValidationException $localFailure) {
            // Local auth failed — try the directory before giving up.
            $authenticator = app(\App\Services\LdapAuthenticator::class);

            try {
                $user = $authenticator->attempt(
                    (string) ($data['email'] ?? ''),
                    (string) ($data['password'] ?? '')
                );
            } catch (\RuntimeException $serverError) {
                Notification::make()
                    ->title('Directory sign-in problem')
                    ->body($serverError->getMessage())
                    ->danger()
                    ->send();

                return null;
            }

            if (! $user) {
                throw $localFailure;
            }

            \Filament\Facades\Filament::auth()->login($user, (bool) ($data['remember'] ?? false));
            session()->regenerate();

            return app(LoginResponse::class);
        }
    }
    
}
