<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Providers;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;


/**
 * Auth integrations generated by Fixzy SysMaker.
 *
 * Registers SSO routes and applies runtime configuration from the
 * fixzy_settings table (admin-editable), so credentials never live
 * in committed files.
 */
class AuthIntegrationsServiceProvider extends ServiceProvider
{
    /**
     * Register auth integration routes and apply runtime Google config.
     */
    public function boot(): void
    {
        $this->registerRoutes();
        
    }

    protected function registerRoutes(): void
    {
        if (! $this->app->runningInConsole()) {
            // Routes are registered lazily so the app boots even before
            // migrations run (e.g. during first-time setup).
            Route::middleware('web')->group(function (): void {
                
            });
        }
    }

    
}
