<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace App\Filament\Resources\IndukExtras\Schemas;



use Illuminate\Contracts\View\View;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;

/**
 * Generated form schema fragment for this table's fields.
 */
class IndukExtraForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make("")
                ->columns([
        'default' => 1,
        'md' => 2,
        
    ])
                ->schema([
				TextInput::make('id')
    ->integer()
    ->maxLength(255)
    ->label('ID')
    ->trim(),
                TextInput::make('catatan')
    ->maxLength(255)
    ->required()->markAsRequired()
    ->label('Note')
    ->trim(),
                Select::make('fk_induk')
    ->unique(ignoreRecord: true)
    ->label('Parent')
    ->relationship('induk', 'nama_induk')
    ,
                ])
                ->columnSpanFull(),
        ]);
    }
}