<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\HasAudits;

use App\Models\Concerns\HasApproval;
use App\Models\Concerns\HasNumbering;

/**
 * Generated Eloquent model for the log_penting table.
 */
class LogPenting extends Model 
{
	use HasFactory;
    use HasAudits;
    use SoftDeletes;
    
    use HasApproval;
    use HasNumbering;

    protected static function numberingConfig(): array
    {
        return ['field' => 'ticket_no', 'prefix' => 'TKT', 'date_token' => '', 'width' => 6, 'reset' => 'never'];
    }

    
    /**
     *
     * @var string
     */
    protected $table = 'log_penting';
    /**
     *
     * @var string
     */
    protected $primaryKey = 'id';
    /**
     *
     * @var array<int, string>
     */
    protected $fillable = [
        
        'perihal',
        'perihal_status',
        'ticket_no'
    
    ];
    
    
    /** Approval workflow (Fixzy SysMaker Approvals module) — generated. */
    public const APPROVAL_STATUS_FIELD = 'perihal_status';
    public const APPROVAL_INITIAL = 'draft';

    public const APPROVAL_STATUSES = [
        'draft' => ['label' => 'Draft', 'color' => 'gray', 'final' => false],
        'approved' => ['label' => 'Approved', 'color' => 'success', 'final' => true],
    ];

    public const APPROVAL_TRANSITIONS = [
        ['from' => 'draft', 'to' => 'approved', 'label' => 'Approve', 'roles' => 'admin', 'require_comment' => true, 'notify' => 'admin'],
    ];

	




}
