<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Resources\Kategoris\RelationManagers;

use App\Filament\Resources\Kategoris\KategoriResource;
use Filament\Actions\CreateAction;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Table;

/**
 * Generated relation manager for Kategori children of the parent record.
 */
class KategoriRelationManager extends RelationManager
{
    protected static string $relationship = 'children';
    
    protected static ?string $relatedResource = KategoriResource::class;

    /**
     * Child record table with a create header action.
     *
     * @param  Table  $table  The relation table instance.
     * @return  Table  The configured table.
     */
    public function table(Table $table): Table
    {
        return $table
            ->headerActions([
                CreateAction::make(),
            ]);
    }
}
