<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

/**
 * Locale switcher middleware (Fixzy SysMaker generated code).
 *
 * Reads the user's chosen locale from the session (set via the
 * language switcher in the user menu) and applies it to the whole
 * request. Falls back to the project default.
 */
class SetLocale
{
    /**
     * Apply the session locale (en/ms) to the application for this request.
     *
     * @param  Request  $request  Incoming request.
     * @param  Closure  $next  Next middleware handler.
     * @return  mixed  The downstream response.
     */
    public function handle(Request $request, Closure $next)
    {
        $supported = ['en', 'ms'];
        $locale = $request->session()->get('fixzy_locale', 'ms');
        if (! in_array($locale, $supported, true)) {
            $locale = 'ms';
        }
        App::setLocale($locale);

        return $next($request);
    }
}
