<x-filament-panels::page>
<div style="display:flex; flex-wrap:wrap; margin:-8px;">
        <a href="/admin/users" style="box-sizing:border-box; width:calc(50.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1.15rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Users</a>
        <a href="/admin/projek" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Projek</a>
        <a href="/admin/tugas" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Tugas</a>
        <a href="/admin/nota" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Nota</a>
        <a href="/admin/kategori" style="box-sizing:border-box; width:calc(25.0000% - 16px); height:100px; margin:8px; border:1px solid #e5e7eb; border-radius:12px; padding:16px; text-decoration:none; color:inherit; background:#fff; box-shadow:0 1px 2px rgba(0,0,0,.05); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:1rem; text-align:center;" class="dark:border-gray-700 dark:bg-gray-800">Kategori</a>
</div>
</x-filament-panels::page>
