<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Fakulti;
use App\Models\Bilik;
use App\Models\SlotBilik;
use App\Models\Tempahan;

class DatabaseSeeder extends Seeder {
    public function run(): void {
        // 1. Create Test User (Super Admin)
        $user = User::firstOrCreate(
            ['email' => 'admin@admin.com'],
            ['name' => 'Super Admin', 'password' => bcrypt('password')]
        );

        // Assign the Super Admin Role
        $role = \Spatie\Permission\Models\Role::firstOrCreate([
            'name' => 'super_admin',
            'guard_name' => 'web'
        ]);
        $user->assignRole($role);


        // Seed Fakulti (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                Fakulti::factory()->create();
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed Bilik (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                Bilik::factory()->create();
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed SlotBilik (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                SlotBilik::factory()->create([
                    'bilik_id' => Bilik::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed Tempahan (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                Tempahan::factory()->create([
                    'room_number' => Bilik::inRandomOrder()->first()?->id ?? null,
                    'slot' => SlotBilik::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Generate Shield permissions (non-interactive).
        \Illuminate\Support\Facades\Artisan::call('shield:generate', [
            '--all' => true, '--panel' => 'admin', '--option' => 'permissions',
        ]);

        // Filament Shield Security
        $this->call(ShieldSeeder::class);

        // Admins group: full panel access via Shield role
        $adminsRole = \Spatie\Permission\Models\Role::firstOrCreate([
            'name' => 'admins',
            'guard_name' => 'web'
        ]);
        $adminsRole->syncPermissions(\Spatie\Permission\Models\Permission::all());
    }
}