<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace App\Filament\Resources\Characters\Schemas;



use Illuminate\Contracts\View\View;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Section;
use Filament\Forms\Components\TextInput;

/**
 * Generated form schema fragment for this table's fields.
 */
class CharacterForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make("")
                ->columns([
        'default' => 1,
        'md' => 2,
        
    ])
                ->schema([
				TextInput::make('id')
    ->integer()
    ->maxLength(255)
    ->label('ID')
    ->trim(),
                TextInput::make('nama_watak')
    ->maxLength(255)
    ->required()->markAsRequired()
    ->label('Character Name')
    ->trim(),
                ])
                ->columnSpanFull(),
        ]);
    }
}