<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Kategori;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Kategori>
 */
class KategoriFactory extends Factory
{
    protected $model = Kategori::class;

    public function definition(): array
    {
        return [
            'nama_kategori' => fake()->name(),
            'parent_kategori_id' => \App\Models\Kategori::inRandomOrder()->value('id'),
        ];
    }
}
