<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Console\Commands;

use Illuminate\Console\Command;

class ScheduledWorkflowCommand extends Command
{
    protected $signature = 'fixzy:scheduled-workflow';

    protected $description = 'Run the Fixzy SysMaker scheduled workflow (on_scheduled_task hook)';

    public function handle(): int
    {
        \DB::table('sessions')
            ->where('last_activity', '<', 100)
            ->delete();
        foreach ((array) $pending_list as $__wf_loopItem) {
            try {
                \DB::table('sessions')->insert([
                    'id' => 'loop-ok',
                    'ip_address' => $__wf_loopItem,
                ]);
            } catch (\Throwable $e) {
                // loop item failed
            }
        }

        return self::SUCCESS;
    }
}
