<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Imports;

use App\Models\Fakulti;

use Filament\Actions\Imports\ImportColumn;
use Filament\Actions\Imports\Importer;
use Filament\Actions\Imports\Models\Import;
use Illuminate\Support\Number;
use Filament\Forms\Components\Checkbox;

/**
 * Generated importer for Fakulti rows from CSV/XLSX.
 */
class FakultiImporter extends Importer
{
    protected static ?string $model = Fakulti::class;

    /**
     * Mappable import columns with type casts and rules.
     * @return  array  ImportColumn definitions.
     */
    public static function getColumns(): array
    {
        return [
            ImportColumn::make('id')
                ->label('Id')
                ->numeric()
                ->integer()
                ->ignoreBlankState()
                ->rules(['integer'])
                ->examples(['1', '2'])
                ->exampleHeader('Id'),

            ImportColumn::make('nama_fakulti')
                ->label('Nama Fakulti')
                ->requiredMapping()
                ->ignoreBlankState()
                ->rules(['required', 'max:150'])
                ->examples(['Sample Nama Fakulti 1', 'Sample Nama Fakulti 2'])
                ->exampleHeader('Nama Fakulti'),

            ImportColumn::make('kod_fakulti')
                ->label('Kod Fakulti')
                ->ignoreBlankState()
                ->rules(['max:20'])
                ->examples(['Sample Kod Fakulti 1', 'Sample Kod Fakulti 2'])
                ->exampleHeader('Kod Fakulti'),
        ];
    }

    /**
     * Resolve which record this imported row maps to (generated custom logic).
     * @return  ?Fakulti  Resolved record instance.
     */
    public function resolveRecord(): ?Fakulti
    {
    
        return Fakulti::firstOrNew([
            'kod_fakulti' => $this->data['kod_fakulti']
        ]);
    }

    /**
     * Notification body shown when the import finishes.
     *
     * @param  Import  $import  The completed import job.
     * @return  string  Human-readable completion summary.
     */
    public static function getCompletedNotificationBody(Import $import): string
    {
        $body = 'Your Fakulti import has completed and ' . Number::format($import->successful_rows) . ' ' . str('row')->plural($import->successful_rows) . ' imported.';

        if ($failedRowsCount = $import->getFailedRowsCount()) {
            $body .= ' ' . Number::format($failedRowsCount) . ' ' . str('row')->plural($failedRowsCount) . ' failed to import.';
        }

        return $body;
    }
    
    /**
     * Extra options form shown before importing (dry run / update existing).
     * @return  array  Form component definitions.
     */
    public static function getOptionsFormComponents(): array
    {
        return [
            Checkbox::make('updateExisting')
                ->label('Update existing records'),
        ];
    }

}
