<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Resources\MatrixRecords\Pages;

use App\Filament\Resources\MatrixRecords\MatrixRecordResource;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\ListRecords;

use Filament\Support\Facades\FilamentView;
use Illuminate\Contracts\View\View;
use Illuminate\Contracts\Support\Htmlable;

/**
 * Generated list page for the MatrixRecord resource.
 */
class ListMatrixRecords extends ListRecords
{
    protected static string $resource = MatrixRecordResource::class;

    /**
     * Page heading.
     * @return  string | Htmlable  The list page title.
     */
    public function getTitle(): string | Htmlable
    {
        return 'Matrix Records'; 
    }
    
    protected function getHeaderActions(): array
    {
        return [
            CreateAction::make(),
        ];
    }
    
    
    
    /**
     * Render the list, optionally stacking row actions vertically via a CSS hook.
     * @return  View  The page view.
     */
    public function render(): View
    {
        

        

        return parent::render();
    }
    
    
}
