<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Induk;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Induk>
 */
class IndukFactory extends Factory
{
    protected $model = Induk::class;

    public function definition(): array
    {
        return [
            'nama_induk' => fake()->name(),
            'meta_decimal' => fake()->randomFloat(2, 10, 1000),
            'meta_date' => fake()->date(),
            'lk_watak' => \App\Models\Character::inRandomOrder()->value('id'),
        ];
    }
}
