<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Pokok;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Pokok>
 */
class PokokFactory extends Factory
{
    protected $model = Pokok::class;

    public function definition(): array
    {
        return [
            'nama_pokok' => fake()->name(),
            'parent_id' => \App\Models\Pokok::inRandomOrder()->value('id'),
        ];
    }
}
