<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\DokumenBerjeni;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\DokumenBerjeni>
 */
class DokumenBerjeniFactory extends Factory
{
    protected $model = DokumenBerjeni::class;

    public function definition(): array
    {
        return [
            'tajuk' => fake()->sentence(4),
            'lampiran' => fake()->word(),
            'pemilik' => \App\Models\User::inRandomOrder()->value('id'),
        ];
    }
}
