<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\Students\RelationManagers;

use App\Filament\Resources\StudentDocuments\StudentDocumentResource;
use Filament\Actions\CreateAction;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables\Table;

/**
 * Generated relation manager for StudentDocument children of the parent record.
 */
class StudentDocumentRelationManager extends RelationManager
{
    protected static string $relationship = 'studentDocuments';
    
    protected static ?string $title = 'Dokumen Pelajar';
    
    
    protected static ?string $relatedResource = StudentDocumentResource::class;

    /**
     * Child record table with a create header action.
     *
     * @param  Table  $table  The relation table instance.
     * @return  Table  The configured table.
     */
    public function table(Table $table): Table
    {
        return $table
            ->headerActions([
                CreateAction::make(),
            ]);
    }
}
