<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace App\Filament\Resources\PelajarTests\Schemas;

use App\Filament\Resources\Faculties\FacultyResource;

use Illuminate\Contracts\View\View;
use Filament\Schemas\Schema;
use Filament\Pages\Page;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Section;
use Filament\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Repeater;

/**
 * Generated form schema fragment for this table's fields.
 */
class PelajarTestForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make("PelajarTest")
                ->columns(fn (Page $livewire) => $livewire->gridColumns ?? 2)
                ->schema([
				TextInput::make('id')
    ->integer()
    ->readOnly()
    ->maxLength(11)
    ->label('ID')
    ->trim(),
                TextInput::make('nama_penuh')
    ->maxLength(150)
    ->required()->markAsRequired()
    ->helperText('Isikan nama penuh seperti didalam kad pengenalan')
    ->label('Full Name')
    ->trim(),
                Select::make('fakulti_id')
    ->label('Faculty ID')
    ->searchable()
    ->preload()
    ->relationship('faculty', 'nama_fakulti')
    ->live()
    ->suffixActions([
    Action::make('view_fakulti')
        ->icon('heroicon-o-eye')
        ->modalContent(fn (Get $get): ?View => $get('fakulti_id') ? view('filament.components.modal-iframe', ['src' => FacultyResource::getUrl('edit', ['record' => $get('fakulti_id')]) . '?iframe=1']) : null)
        ->modalWidth('6xl')
        ->modalSubmitAction(false)
        ->hidden(fn (Get $get): bool => !$get('fakulti_id')),
    Action::make('create_fakulti')
        ->icon('heroicon-o-plus')
        ->modalContent(fn (): View => view('filament.components.modal-iframe', ['src' => FacultyResource::getUrl('create') . '?iframe=1']))
        ->modalWidth('6xl')
        ->modalSubmitAction(false),
])
    ,
                TextInput::make('no_matrik')
    ->maxLength(20)
    ->required()->markAsRequired()
    ->unique(ignoreRecord: true)
    ->label('Matric Number')
    ->trim(),
                Repeater::make('email')
    ->label('Email')
    ->simple(
        TextInput::make('email')->email()->unique(ignoreRecord: true),
    )
    ->reorderable(false),
                TextInput::make('tarikh_daftar')
    ->default('NULL')
    ->label('Registration Date')
    ->trim(),
                FileUpload::make('gambar_profil')
    ->label('Profile Photo')
    ->image()
    ->imageEditor()
    ->directory('gambar-profil')
    ->disk('public')
    ->downloadable(),
                FileUpload::make('surat_tawaran')
    ->label('Offer Letter')
    ->directory('surat-tawaran')
    ->disk('public')
    ->acceptedFileTypes(['image/jpeg', 'image/jpeg', 'application/pdf'])
    ->downloadable()
    ->openable(),
                TextInput::make('created_at')
    ->label('Created At')
    ->trim(),
                TextInput::make('updated_at')
    ->label('Updated At')
    ->trim(),
                TextInput::make('deleted_at')
    ->label('Deleted At')
    ->trim(),
                ])
                ->columnSpanFull(),
        ]);
    }
}