<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Character;
use App\Models\MatrixRecord;
use App\Models\Pokok;
use App\Models\Induk;
use App\Models\Anak;
use App\Models\AnakKad;
use App\Models\IndukExtra;

class DatabaseSeeder extends Seeder {
    public function run(): void {
        // 1. Create Test User (Super Admin)
        $user = User::firstOrCreate(
            ['email' => 'admin@admin.com'],
            ['name' => 'Super Admin', 'password' => bcrypt('password')]
        );

        // Assign the Super Admin Role
        $role = \Spatie\Permission\Models\Role::firstOrCreate([
            'name' => 'super_admin',
            'guard_name' => 'web'
        ]);
        $user->assignRole($role);


        // Seed Character (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                Character::factory()->create();
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed MatrixRecord (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                MatrixRecord::factory()->create([
                    'lk_dropdown' => Character::inRandomOrder()->first()?->id ?? null,
                    'lk_radios' => Character::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed Pokok (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                Pokok::factory()->create([
                    'parent_id' => Pokok::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed Induk (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                Induk::factory()->create([
                    'lk_watak' => Character::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed Anak (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                Anak::factory()->create([
                    'fk_induk' => Induk::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed AnakKad (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                AnakKad::factory()->create([
                    'fk_induk' => Induk::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Seed IndukExtra (Kalis Ralat Unique Constraint)
        for ($i = 0; $i < 20; $i++) {
            try {
                IndukExtra::factory()->create([
                    'fk_induk' => Induk::inRandomOrder()->first()?->id ?? null
                ]);
            } catch (\Exception $e) {
                // Ignore if data is duplicated or violates a Unique Constraint
            }
        }

        // Filament Shield Security
        $this->call(ShieldSeeder::class);
    }
}