<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\HasAudits;


/**
 * Generated Eloquent model for the pelajar table.
 */
class Student extends Model 
{
	use HasFactory;
    use HasAudits;
    use SoftDeletes;
    
    
    /**
     *
     * @var string
     */
    protected $table = 'pelajar';
    /**
     *
     * @var string
     */
    protected $primaryKey = 'id';
    /**
     *
     * @var array<int, string>
     */
    protected $fillable = [
        
        'fakulti_id',
        'nama_penuh',
        'no_matrik',
        'email',
        'tarikh_daftar',
        'gambar_profil',
        'surat_tawaran'
    
    ];
    

    protected function casts(): array
    {
        return [
            'email' => 'array',
        ];
    }
    


    public function studentProfile()
    {
        return $this->hasOne(StudentProfile::class, 'pelajar_id', 'id');
    }
    public function studentDocuments()
    {
        return $this->hasMany(StudentDocument::class, 'pelajar_id', 'id');
    }
    public function courseRegistrations()
    {
        return $this->hasMany(CourseRegistration::class, 'pelajar_id', 'id');
    }
    public function examResults()
    {
        return $this->hasMany(ExamResult::class, 'pelajar_id', 'id');
    }
    public function faculty()
    {
        return $this->belongsTo(Faculty::class, 'fakulti_id', 'id');
    }	




}
