<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('semua_field', function (Blueprint $table) {
            $table->id();
            $table->string('min_len_teks', 50);
            $table->string('fixed_len_kod', 8);
            $table->string('prefix_gaji', 120);
            $table->string('suffix_unit', 120);
            $table->string('suffix_icon', 120);
            $table->string('suffix_icon_color', 120);
            $table->string('multi_rules', 120);
            $table->string('avatar_bulat', 255);
            $table->string('teks_biasa', 120);
            $table->string('emel', 150);
            $table->string('katalaluan', 100);
            $table->string('telefon', 30);
            $table->string('pautan', 255);
            $table->string('berkas_topeng', 20);
            $table->integer('umur');
            $table->decimal('gaji', 12, 2);
            $table->integer('kod_zero');
            $table->string('unik_kod', 40)->unique();
            $table->text('cerita');
            $table->text('rich_teks');
            $table->boolean('aktif');
            $table->string('status', 255);
            $table->string('tag_multi', 255);
            $table->dateTime('tarikh_masa');
            $table->json('emel_berulang');
            $table->json('butiran');
            $table->string('helper_cara', 80);
            $table->string('auto_off', 50);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('semua_field');
    }
};