<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\HasAudits;


/**
 * Generated Eloquent model for the jana_bil table.
 */
class JanaBil extends Model 
{
	use HasFactory;
    use HasAudits;
    use SoftDeletes;
    
    
    /**
     *
     * @var string
     */
    protected $table = 'jana_bil';
    /**
     *
     * @var string
     */
    protected $primaryKey = 'id';
    /**
     *
     * @var array<int, string>
     */
    protected $fillable = [
        
        'bil_1',
        'bil_2',
        'jumlah'
    
    ];
    
    

	




    protected static function boot()
    {
        parent::boot();

        static::saved(function ($model) {
            $v = \DB::selectOne(str_replace('##ID##', (string) $model->getKey(), 'SELECT {bil_1} + {bil_2}'));
            if ($v !== null) { $model->{'jumlah'} = array_values((array) $v)[0] ?? null; }
            $model->saveQuietly();
        });
    }

}
