<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\HasAudits;


/**
 * Generated Eloquent model for the dokumen_berjenis table.
 */
class DokumenBerjeni extends Model 
{
	use HasFactory;
    use HasAudits;
    use SoftDeletes;
    
    
    /**
     *
     * @var string
     */
    protected $table = 'dokumen_berjenis';
    /**
     *
     * @var string
     */
    protected $primaryKey = 'id';
    /**
     *
     * @var array<int, string>
     */
    protected $fillable = [
        
        'tajuk',
        'lampiran',
        'pemilik'
    
    ];
    

    protected function casts(): array
    {
        return [
            'lampiran' => 'array',
        ];
    }
    

    public function attachments()
    {
        return $this->morphMany(\App\Models\Attachment::class, 'record')->latest('id');
    }


    public function user()
    {
        return $this->belongsTo(User::class, 'pemilik', 'id');
    }	




}
