<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Resources\Characters\Tables;



use App\Models\Character;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\RestoreAction;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Illuminate\Contracts\View\View;


/**
 * Generated table configuration fragment for this table.
 */
class CharactersTable
{
    /**
     * Apply pagination, columns and display options to the table.
     *
     * @param  Table  $table  The table instance to configure.
     * @return  Table  The configured table.
     */
    public static function configure(Table $table): Table
    {
        return $table
            
            ->paginationMode(\Filament\Tables\Enums\PaginationMode::Simple)
            
            
            ->recordUrl(null)
            ->description('')
            ->columns([
                TextColumn::make('id')
                    ->label('Id')
                    ->sortable()
                    ->limit(50, end: ' (more)')
                    ->searchable()
                    ->toggleable()
                    ->numeric(),
                TextColumn::make('nama_watak')
                    ->label('Character Name')
                    ->sortable()
                    ->limit(50, end: ' (more)')
                    ->searchable()
                    ->toggleable()
            ])
            
            ->filters([
                TrashedFilter::make(),
            ])
            ->recordActions([

                   
                    
                EditAction::make(),
                DeleteAction::make(),
                
                RestoreAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                DeleteBulkAction::make(),
            ]),
            ]);
    }
}