<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\StudentDocument;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\StudentDocument>
 */
class StudentDocumentFactory extends Factory
{
    protected $model = StudentDocument::class;

    public function definition(): array
    {
        return [
            'pelajar_id' => \App\Models\Student::inRandomOrder()->value('id'),
            'nama_fail' => fake()->name(),
            'path_fail' => fake()->word(),
            'jenis_dokumen' => fake()->word(),
            'tarikh_muatnaik' => fake()->dateTimeThisYear(),
        ];
    }
}
