<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\TvLeftimages\Tables;



use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\ForceDeleteAction;
use Filament\Actions\RestoreAction;
use Filament\Tables\Table;
use Filament\Tables\Columns\ImageColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Columns\Layout\Split;
use Filament\Tables\Columns\Layout\Stack;
use Filament\Support\Enums\TextSize;
use Illuminate\Contracts\View\View;


/**
 * Generated table configuration fragment for this table.
 */
class TvLeftimagesTable
{
    /**
     * Apply pagination, columns and display options to the table.
     *
     * @param  Table  $table  The table instance to configure.
     * @return  Table  The configured table.
     */
    public static function configure(Table $table): Table
    {
        return $table
            
            
            
            
            
            ->description('')
            ->columns([
                Split::make([
                    ImageColumn::make('gambar')
                    ->label('Gambar')
                    ->circular()
                    ->imageWidth(60)
                    ->toggleable(),
                    Stack::make([
                        TextColumn::make('nama_fakulti')
                    ->label('Nama Fakulti')
                    ->sortable()
                    ->limit(50, end: ' (more)')
                    ->color('success')
                    ->size(TextSize::Medium)
                    ->searchable()
                    ->toggleable()
                    ->alignCenter()
                    ]),
                ])->from('md')
            ])
            ->when((bool) request()->query('print'), fn (Table $table) => $table->paginated(false),)
            ->filters([
                TrashedFilter::make(),
            ])
            ->recordActions([

                   
                    
                
                
                ForceDeleteAction::make(),
                RestoreAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                DeleteBulkAction::make(),
            ]),
            ]);
    }
}