<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace App\Filament\Resources\LeadPipelines\Schemas;



use Illuminate\Contracts\View\View;
use Filament\Schemas\Schema;
use Filament\Pages\Page;
use Filament\Schemas\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;

/**
 * Generated form schema fragment for this table's fields.
 */
class LeadPipelineForm
{
    /**
     * Build the form components for the schema.
     *
     * @param  Schema  $schema  The form schema to fill.
     * @return  Schema  The configured schema.
     */
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make("Lead Pipeline")
                ->columns(fn (Page $livewire) => $livewire->gridColumns ?? 2)
                ->schema([
				TextInput::make('id')
    ->integer()
    ->readOnly()
    ->maxLength(11)
    ->label('ID')
    ->trim(),
                TextInput::make('created_at')
    ->readOnly()
    ->label('Created At')
    ->trim(),
                TextInput::make('updated_at')
    ->readOnly()
    ->label('Updated At')
    ->trim(),
                TextInput::make('deleted_at')
    ->readOnly()
    ->label('Deleted At')
    ->trim(),
                TextInput::make('created_by')
    ->integer()
    ->readOnly()
    ->maxLength(20)
    ->label('Created By')
    ->trim(),
                TextInput::make('updated_by')
    ->integer()
    ->readOnly()
    ->maxLength(20)
    ->label('Updated By')
    ->trim(),
                TextInput::make('deleted_by')
    ->integer()
    ->readOnly()
    ->maxLength(20)
    ->label('Deleted By')
    ->trim(),
                TextInput::make('lead_name')
    ->maxLength(150)
    ->required()->markAsRequired()
    ->label('Lead Name')
    ->trim(),
                TextInput::make('contact_id')
    ->integer()
    ->label('Contact')
    ->trim(),
                Select::make('source')
    ->label('Source')
    ->options(['website|referral|cold_call|event|social_media|other' => 'Website|referral|cold Call|event|social Media|other'])
    ,
                Select::make('pipeline_stage')
    ->default('new')
    ->label('Stage')
    ->options(['new|contacted|qualified|proposal|won|lost' => 'New|contacted|qualified|proposal|won|lost'])
    ,
                TextInput::make('estimated_value')
    ->numeric()->rule('decimal:0,2')
    ->label('Estimated Value')
    ->trim(),
                TextInput::make('expected_close_date')
    ->label('Expected Close')
    ->trim(),
                TextInput::make('owner_name')
    ->maxLength(150)
    ->label('Owner')
    ->trim(),
                ])
                ->columnSpanFull(),
        ]);
    }
}