<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\AnakKads;

use App\Filament\Resources\AnakKads\Pages\CreateAnakKad;
use App\Filament\Resources\AnakKads\Pages\EditAnakKad;
use App\Filament\Resources\AnakKads\Pages\ListAnakKads;
use App\Filament\Resources\AnakKads\Schemas\AnakKadForm;
use App\Filament\Resources\AnakKads\Tables\AnakKadsTable;
use App\Models\AnakKad;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;



use App\Filament\Imports\AnakKadImporter;
use Filament\Actions\ImportAction;
use App\Filament\Exports\AnakKadExporter;
use Filament\Actions\ExportAction;




/**
 * Generated Filament resource for the AnakKad model.
 */
class AnakKadResource extends Resource
{
    protected static ?string $model = AnakKad::class;
    
    

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    
    
    

    /**
     * Delegate the form definition to the generated form schema class.
     *
     * @param  Schema  $schema  The resource form schema.
     * @return  Schema  The configured schema.
     */
    public static function form(Schema $schema): Schema
    {
        return AnakKadForm::configure($schema);
    }

    /**
     * Delegate the table definition and add import/export/print header actions.
     *
     * @param  Table  $table  The resource table instance.
     * @return  Table  The configured table.
     */
    public static function table(Table $table): Table
    {
        return AnakKadsTable::configure($table)
		        ->headerActions([
ImportAction::make()->importer(AnakKadImporter::class),
ExportAction::make()->exporter(AnakKadExporter::class)
                /*->enableVisibleTableColumnsByDefault()*/,
			
        ]);
    }

    /**
     * Relation managers shown on the resource, gated by the current user's permissions.
     * @return  array  Relation manager class names.
     */
    public static function getRelations(): array
    {
        $relations = [
            
        ];
		

    // Only add AuditsRelationManager if the user is allowed to view it
    
	
	return $relations;
    }

    /**
     * Route bindings for the resource's list, create and edit pages.
     * @return  array  Page name to route mapping.
     */
    public static function getPages(): array
    {
        return [
            'index' => ListAnakKads::route('/'),
            'create' => CreateAnakKad::route('/create'),
            'edit' => EditAnakKad::route('/{record}/edit'),
        ];
    }
	
    // 1. Set the URL
    protected static ?string $slug = 'anakkads';

    // 2. Set the label for a single record
    /**
     * Singular label for the model.
     * @return  string  Singular model label.
     */
    public static function getModelLabel(): string
    {
        return 'AnakKad';
    }

    // 3. Set the label for multiple records (main resource page title)
    /**
     * Plural label used in the navigation menu.
     * @return  string  Plural model label.
     */
    public static function getPluralModelLabel(): string
    {
        return 'AnakKads';
    }
	
    

    

    
}
