<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('aduan', function (Blueprint $table) {
            $table->id();
            $table->string('txt_plain', 255);
            $table->string('txt_email', 255);
            $table->text('txt_area')->nullable();
            $table->text('txt_rich')->nullable();
            $table->boolean('bool_urgent')->nullable();
            $table->string('opt_category', 255)->nullable();
            $table->string('opt_channels', 255)->nullable();
            $table->string('opt_priority', 255)->nullable();
            $table->foreignId('lk_watak')->nullable();
            $table->foreignId('lk_watak_radio')->nullable();
            $table->json('rep_notes')->nullable();
            $table->decimal('num_amount', 10, 2)->nullable();
            $table->date('dt_event')->nullable();
            $table->dateTime('dt_report')->nullable();
            $table->string('aduan_status', 255)->nullable();
            $table->string('img_proof', 255);
            $table->string('doc_form', 255)->nullable();
            $table->text('files_extra')->nullable();
            $table->string('map_place', 255)->nullable();
            $table->string('vid_evidence', 255)->nullable();
            $table->string('internal_note', 255)->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('aduan');
    }
};