<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */

namespace App\Filament\Resources\Anaks\Pages;

use App\Filament\Resources\Anaks\AnakResource;
use Filament\Resources\Pages\CreateRecord;

/**
 * Generated create page for the Anak resource.
 */
class CreateAnak extends CreateRecord
{
    protected static string $resource = AnakResource::class;

    
    
    protected function getHeaderActions(): array
    {
        return [
            $this->getCreateFormAction()
                 ->formId('form'),
            $this->getCreateAnotherFormAction()
                 ->formId('form'),
            $this->getCancelFormAction(),
        ];
    }
    
    
    /**
     * Use the stripped-down iframe layout when the page is embedded.
     * @return  string  Blade layout name.
     */
    public function getLayout(): string
    {
        if (session('is_in_iframe')) {
            return 'filament.layouts.custom-iframe-layout';
        }
        
        return parent::getLayout();
    }


    protected function getFormActions(): array
    {
        return [];
    }
}