<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Apache License 2.0 (see https://www.apache.org/licenses/LICENSE-2.0).
 */

namespace App\Filament\Resources\Anaks\Pages;

use App\Filament\Resources\Anaks\AnakResource;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;
use Filament\Support\Facades\FilamentView;
use Illuminate\Contracts\View\View;
use Illuminate\Contracts\Support\Htmlable;

/**
 * Generated list page for the Anak resource.
 */
class ListAnaks extends ListRecords
{
    protected static string $resource = AnakResource::class;

    /**
     * Page heading.
     * @return  string | Htmlable  The list page title.
     */
    public function getTitle(): string | Htmlable
    {
        return 'Anaks'; 
    }
    
    protected function getHeaderActions(): array
    {
        return [
            CreateAction::make()
    ->when(
        session('is_in_iframe'),
        fn (CreateAction $action) => $action->url(fn (): string => static::getResource()::getUrl('create', [
                    'fk_induk' => request()->query('fk_induk')
                ]))
    )
        ];
    }
    
    
    protected function getTableQuery(): Builder
    {
        $query = parent::getTableQuery();
        
        if ($fkValue = request()->query('fk_induk')) {
            $query->where('fk_induk', $fkValue);
        }
        return $query;
    }
    
    /**
     * Render the list, optionally stacking row actions vertically via a CSS hook.
     * @return  View  The page view.
     */
    public function render(): View
    {
        

        

        return parent::render();
    }
    
    
    /**
     * Remember iframe embedding (and foreign key) in the session.
     */
    public function mount(): void
    {
        parent::mount();

        if (request()->has('iframe')) {
            session(['is_in_iframe' => true]);
            session(['foreignkey' => 'fk_induk']);
        } else {
            session()->forget('is_in_iframe');
            session()->forget('foreignkey');
        }
    }
    
    /**
     * Use the stripped-down iframe layout when the session iframe flag is set.
     * @return  string  Blade layout name.
     */
    public function getLayout(): string
    {
        if (session('is_in_iframe')) {
            return 'filament.layouts.custom-iframe-layout';
        }
        return parent::getLayout();
    }
}
