<?php

/**
 * Generated by Fixzy SysMaker — © 2025 Mohd Hafizi Mohammad Nor.
 * Licensed under the Non-Commercial Software License (see LICENSE.md).
 * This attribution banner must not be removed or altered.
 */
namespace Database\Factories;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Syarikat;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Syarikat>
 */
class SyarikatFactory extends Factory
{
    protected $model = Syarikat::class;

    public function definition(): array
    {
        return [
            'nama_syarikat' => fake()->name(),
        ];
    }
}
